// API: Авто-генерация кейсов (УРОВЕНЬ 3, функция 15)
import { NextRequest, NextResponse } from 'next/server';
import { generateCaseStudy } from '@/lib/advanced-ai-engine';
import { db } from '@/lib/db';
import { nanoid } from 'nanoid';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { campaignData, userId, saveToDb } = body;
    
    if (!campaignData || !userId) {
      return NextResponse.json(
        { error: 'Missing required fields: campaignData, userId' },
        { status: 400 }
      );
    }
    
    const caseStudy = await generateCaseStudy(campaignData, userId);
    
    // Сохраняем в базу если нужно
    let savedCase: Awaited<ReturnType<typeof db.caseStudy.create>> | null = null;
    if (saveToDb) {
      savedCase = await db.caseStudy.create({
        data: {
          id: nanoid(),
          title: caseStudy.title,
          summary: caseStudy.summary,
          screenshots: JSON.stringify(caseStudy.screenshots),
          autoGenerated: true,
          revenue: campaignData.revenue,
          spent: campaignData.spent,
          roi: campaignData.spent > 0 
            ? (campaignData.revenue - campaignData.spent) / campaignData.spent 
            : 0,
          status: 'draft',
          updatedAt: new Date(),
        },
      });
    }
    
    return NextResponse.json({
      success: true,
      caseStudy,
      savedCase,
    });
  } catch (error) {
    console.error('[CaseStudy API] Error:', error);
    return NextResponse.json(
      { error: 'Failed to generate case study', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}

// Получение списка кейсов
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status') || 'published';
    
    const caseStudies = await db.caseStudy.findMany({
      where: { status },
      orderBy: { createdAt: 'desc' },
      take: 20,
    });
    
    return NextResponse.json({
      success: true,
      caseStudies,
    });
  } catch (error) {
    console.error('[CaseStudy API] Error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch case studies' },
      { status: 500 }
    );
  }
}
