'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import {
  Settings,
  Key,
  Palette,
  Bell,
  Shield,
  Globe,
  Moon,
  Sun,
  Contrast,
  RefreshCw,
  Save,
  Volume2,
  VolumeX,
  Bot,
  Zap,
} from 'lucide-react';
import { AIProvidersSettings } from '@/components/settings/ai-providers-settings';
import { useModeStore } from '@/store/mode-store';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

interface AppSettings {
  theme: 'dark' | 'light' | 'high-contrast';
  language: 'ru' | 'en';
  notifications: {
    enabled: boolean;
    sound: boolean;
    desktop: boolean;
    email: boolean;
  };
  riskAssistant: {
    enabled: boolean;
    threshold: 'low' | 'medium' | 'high';
    autoGenerateDisclaimers: boolean;
  };
  automation: {
    autoPauseOnCpa: boolean;
    telegramNotifications: boolean;
    telegramChatId: string;
  };
  voice: {
    enabled: boolean;
    provider: 'browser' | 'elevenlabs';
    voiceId: string;
  };
}

const defaultSettings: AppSettings = {
  theme: 'dark',
  language: 'ru',
  notifications: {
    enabled: true,
    sound: true,
    desktop: false,
    email: false,
  },
  riskAssistant: {
    enabled: true,
    threshold: 'medium',
    autoGenerateDisclaimers: true,
  },
  automation: {
    autoPauseOnCpa: false,
    telegramNotifications: false,
    telegramChatId: '',
  },
  voice: {
    enabled: false,
    provider: 'browser',
    voiceId: '',
  },
};

export function SettingsView() {
  const { uiMode, theme, setTheme } = useModeStore();
  const [settings, setSettings] = useState<AppSettings>(defaultSettings);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  // Загрузка настроек
  useEffect(() => {
    const loadSettings = async () => {
      try {
        const response = await fetch('/api/settings');
        if (response.ok) {
          const data = await response.json();
          setSettings({ ...defaultSettings, ...data });
        }
      } catch (error) {
        console.error('Failed to load settings:', error);
      } finally {
        setIsLoading(false);
      }
    };
    loadSettings();
  }, []);

  // Сохранение настроек
  const saveSettings = async () => {
    setIsSaving(true);
    try {
      const response = await fetch('/api/settings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(settings),
      });
      if (response.ok) {
        toast.success('Настройки сохранены');
      } else {
        toast.error('Ошибка сохранения');
      }
    } catch (error) {
      toast.error('Ошибка сохранения');
    } finally {
      setIsSaving(false);
    }
  };

  // Обновление части настроек
  const updateSettings = <K extends keyof AppSettings>(
    key: K,
    value: AppSettings[K]
  ) => {
    setSettings(prev => ({ ...prev, [key]: value }));
  };

  // Тема
  const handleThemeChange = (newTheme: 'dark' | 'light' | 'high-contrast') => {
    updateSettings('theme', newTheme);
    setTheme(newTheme);
    document.documentElement.classList.remove('high-contrast');
    if (newTheme === 'high-contrast') {
      document.documentElement.classList.add('high-contrast');
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-96">
        <RefreshCw className="w-8 h-8 text-[#6C63FF] animate-spin" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Заголовок */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white">Настройки</h1>
          <p className="text-[#8A8A8A]">Конфигурация системы и偏好</p>
        </div>
        <Button
          onClick={saveSettings}
          disabled={isSaving}
          className="bg-[#6C63FF] hover:bg-[#6C63FF]/80"
        >
          {isSaving ? (
            <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
          ) : (
            <Save className="w-4 h-4 mr-2" />
          )}
          Сохранить
        </Button>
      </div>

      <Tabs defaultValue="general" className="space-y-6">
        <TabsList className="bg-[#1E1F26] border-[#2A2B32]">
          <TabsTrigger value="general" className="data-[state=active]:bg-[#6C63FF]">
            <Settings className="w-4 h-4 mr-2" />
            Общие
          </TabsTrigger>
          <TabsTrigger value="ai" className="data-[state=active]:bg-[#6C63FF]">
            <Bot className="w-4 h-4 mr-2" />
            AI Провайдеры
          </TabsTrigger>
          <TabsTrigger value="notifications" className="data-[state=active]:bg-[#6C63FF]">
            <Bell className="w-4 h-4 mr-2" />
            Уведомления
          </TabsTrigger>
          <TabsTrigger value="risk" className="data-[state=active]:bg-[#6C63FF]">
            <Shield className="w-4 h-4 mr-2" />
            Риски
          </TabsTrigger>
          <TabsTrigger value="voice" className="data-[state=active]:bg-[#6C63FF]">
            <Volume2 className="w-4 h-4 mr-2" />
            Голос
          </TabsTrigger>
        </TabsList>

        {/* Общие настройки */}
        <TabsContent value="general" className="space-y-6">
          <Card className="bg-[#14151A] border-[#2A2B32]">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Palette className="w-5 h-5 text-[#6C63FF]" />
                Внешний вид
              </CardTitle>
              <CardDescription className="text-[#8A8A8A]">
                Настройка темы и языка интерфейса
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Тема */}
              <div className="space-y-3">
                <Label className="text-white">Тема оформления</Label>
                <div className="grid grid-cols-3 gap-3">
                  {[
                    { value: 'dark', label: 'Тёмная', icon: Moon },
                    { value: 'light', label: 'Светлая', icon: Sun },
                    { value: 'high-contrast', label: 'Высокий контраст', icon: Contrast },
                  ].map((themeOption) => {
                    const Icon = themeOption.icon;
                    return (
                      <button
                        key={themeOption.value}
                        onClick={() => handleThemeChange(themeOption.value as any)}
                        className={cn(
                          'flex flex-col items-center gap-2 p-4 rounded-lg border transition-all',
                          settings.theme === themeOption.value
                            ? 'border-[#6C63FF] bg-[#6C63FF]/10'
                            : 'border-[#2A2B32] hover:border-[#6C63FF]/50'
                        )}
                      >
                        <Icon className={cn(
                          'w-6 h-6',
                          settings.theme === themeOption.value ? 'text-[#6C63FF]' : 'text-[#8A8A8A]'
                        )} />
                        <span className={cn(
                          'text-sm',
                          settings.theme === themeOption.value ? 'text-white' : 'text-[#8A8A8A]'
                        )}>
                          {themeOption.label}
                        </span>
                      </button>
                    );
                  })}
                </div>
              </div>

              <Separator className="bg-[#2A2B32]" />

              {/* Язык */}
              <div className="flex items-center justify-between">
                <div>
                  <Label className="text-white">Язык интерфейса</Label>
                  <p className="text-sm text-[#8A8A8A]">Язык отображения меню и подсказок</p>
                </div>
                <Select
                  value={settings.language}
                  onValueChange={(v) => updateSettings('language', v as any)}
                >
                  <SelectTrigger className="w-40 bg-[#1E1F26] border-[#2A2B32] text-white">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="bg-[#14151A] border-[#2A2B32]">
                    <SelectItem value="ru">Русский</SelectItem>
                    <SelectItem value="en">English</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
          </Card>

          {/* Автоматизация */}
          <Card className="bg-[#14151A] border-[#2A2B32]">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Zap className="w-5 h-5 text-[#FFB800]" />
                Автоматизация
              </CardTitle>
              <CardDescription className="text-[#8A8A8A]">
                Настройки автоматических процессов
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-white">Авто-пауза при CPA</p>
                  <p className="text-sm text-[#8A8A8A]">Автоматически приостанавливать кампании при достижении лимита стоимости за лид</p>
                </div>
                <Switch
                  checked={settings.automation.autoPauseOnCpa}
                  onCheckedChange={(v) => updateSettings('automation', { ...settings.automation, autoPauseOnCpa: v })}
                />
              </div>

              <Separator className="bg-[#2A2B32]" />

              <div className="flex items-center justify-between">
                <div>
                  <p className="text-white">Telegram уведомления</p>
                  <p className="text-sm text-[#8A8A8A]">Получать уведомления в Telegram</p>
                </div>
                <Switch
                  checked={settings.automation.telegramNotifications}
                  onCheckedChange={(v) => updateSettings('automation', { ...settings.automation, telegramNotifications: v })}
                />
              </div>

              {settings.automation.telegramNotifications && (
                <div className="space-y-2">
                  <Label>Telegram Chat ID</Label>
                  <Input
                    value={settings.automation.telegramChatId}
                    onChange={(e) => updateSettings('automation', { ...settings.automation, telegramChatId: e.target.value })}
                    placeholder="Введите Chat ID"
                    className="bg-[#1E1F26] border-[#2A2B32] text-white"
                  />
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* AI Провайдеры */}
        <TabsContent value="ai">
          <AIProvidersSettings />
        </TabsContent>

        {/* Уведомления */}
        <TabsContent value="notifications" className="space-y-6">
          <Card className="bg-[#14151A] border-[#2A2B32]">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Bell className="w-5 h-5 text-[#FFB800]" />
                Настройки уведомлений
              </CardTitle>
              <CardDescription className="text-[#8A8A8A]">
                Управление способами получения уведомлений
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-white">Включить уведомления</p>
                  <p className="text-sm text-[#8A8A8A]">Общий переключатель уведомлений</p>
                </div>
                <Switch
                  checked={settings.notifications.enabled}
                  onCheckedChange={(v) => updateSettings('notifications', { ...settings.notifications, enabled: v })}
                />
              </div>

              <Separator className="bg-[#2A2B32]" />

              <div className="flex items-center justify-between">
                <div>
                  <p className="text-white">Звуковые уведомления</p>
                  <p className="text-sm text-[#8A8A8A]">Воспроизводить звук при важных событиях</p>
                </div>
                <Switch
                  checked={settings.notifications.sound}
                  onCheckedChange={(v) => updateSettings('notifications', { ...settings.notifications, sound: v })}
                />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <p className="text-white">Desktop уведомления</p>
                  <p className="text-sm text-[#8A8A8A]">Показывать уведомления на рабочем столе</p>
                </div>
                <Switch
                  checked={settings.notifications.desktop}
                  onCheckedChange={(v) => updateSettings('notifications', { ...settings.notifications, desktop: v })}
                />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <p className="text-white">Email уведомления</p>
                  <p className="text-sm text-[#8A8A8A]">Отправлять уведомления на email</p>
                </div>
                <Switch
                  checked={settings.notifications.email}
                  onCheckedChange={(v) => updateSettings('notifications', { ...settings.notifications, email: v })}
                />
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Риски */}
        <TabsContent value="risk" className="space-y-6">
          <Card className="bg-[#14151A] border-[#2A2B32]">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Shield className="w-5 h-5 text-[#FF4D4D]" />
                Риск-ассистент
              </CardTitle>
              <CardDescription className="text-[#8A8A8A]">
                Настройка предупреждений о юридических рисках
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-white">Включить риск-ассистента</p>
                  <p className="text-sm text-[#8A8A8A]">Анализировать кампании на юридические риски</p>
                </div>
                <Switch
                  checked={settings.riskAssistant.enabled}
                  onCheckedChange={(v) => updateSettings('riskAssistant', { ...settings.riskAssistant, enabled: v })}
                />
              </div>

              <Separator className="bg-[#2A2B32]" />

              <div className="space-y-2">
                <Label className="text-white">Порог предупреждений</Label>
                <Select
                  value={settings.riskAssistant.threshold}
                  onValueChange={(v) => updateSettings('riskAssistant', { ...settings.riskAssistant, threshold: v as any })}
                >
                  <SelectTrigger className="bg-[#1E1F26] border-[#2A2B32] text-white">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="bg-[#14151A] border-[#2A2B32]">
                    <SelectItem value="low">
                      <div className="flex items-center gap-2">
                        <div className="w-2 h-2 rounded-full bg-[#00D26A]" />
                        Низкий - только критические риски
                      </div>
                    </SelectItem>
                    <SelectItem value="medium">
                      <div className="flex items-center gap-2">
                        <div className="w-2 h-2 rounded-full bg-[#FFB800]" />
                        Средний - баланс безопасности
                      </div>
                    </SelectItem>
                    <SelectItem value="high">
                      <div className="flex items-center gap-2">
                        <div className="w-2 h-2 rounded-full bg-[#FF4D4D]" />
                        Высокий - максимум предупреждений
                      </div>
                    </SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <p className="text-white">Авто-генерация дисклеймеров</p>
                  <p className="text-sm text-[#8A8A8A]">Автоматически добавлять предупреждения к контенту</p>
                </div>
                <Switch
                  checked={settings.riskAssistant.autoGenerateDisclaimers}
                  onCheckedChange={(v) => updateSettings('riskAssistant', { ...settings.riskAssistant, autoGenerateDisclaimers: v })}
                />
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Голос */}
        <TabsContent value="voice" className="space-y-6">
          <Card className="bg-[#14151A] border-[#2A2B32]">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Volume2 className="w-5 h-5 text-[#00D26A]" />
                Голосовые подсказки
              </CardTitle>
              <CardDescription className="text-[#8A8A8A]">
                Настройка голосового ассистента для новичков
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-white">Включить голосовые подсказки</p>
                  <p className="text-sm text-[#8A8A8A]">Озвучивать подсказки для начинающих пользователей</p>
                </div>
                <Switch
                  checked={settings.voice.enabled}
                  onCheckedChange={(v) => updateSettings('voice', { ...settings.voice, enabled: v })}
                />
              </div>

              {settings.voice.enabled && (
                <>
                  <Separator className="bg-[#2A2B32]" />

                  <div className="space-y-2">
                    <Label className="text-white">Провайдер голоса</Label>
                    <Select
                      value={settings.voice.provider}
                      onValueChange={(v) => updateSettings('voice', { ...settings.voice, provider: v as any })}
                    >
                      <SelectTrigger className="bg-[#1E1F26] border-[#2A2B32] text-white">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="bg-[#14151A] border-[#2A2B32]">
                        <SelectItem value="browser">
                          <div className="flex items-center gap-2">
                            <Globe className="w-4 h-4" />
                            Browser TTS (Бесплатно)
                          </div>
                        </SelectItem>
                        <SelectItem value="elevenlabs">
                          <div className="flex items-center gap-2">
                            <Volume2 className="w-4 h-4" />
                            ElevenLabs (Премиум)
                          </div>
                        </SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  {settings.voice.provider === 'elevenlabs' && (
                    <div className="space-y-2">
                      <Label className="text-white">Voice ID (ElevenLabs)</Label>
                      <Input
                        value={settings.voice.voiceId}
                        onChange={(e) => updateSettings('voice', { ...settings.voice, voiceId: e.target.value })}
                        placeholder="Введите Voice ID"
                        className="bg-[#1E1F26] border-[#2A2B32] text-white"
                      />
                    </div>
                  )}

                  <Button
                    variant="outline"
                    onClick={() => {
                      if ('speechSynthesis' in window) {
                        const utterance = new SpeechSynthesisUtterance('Привет! Это тест голосового ассистента.');
                        utterance.lang = 'ru-RU';
                        speechSynthesis.speak(utterance);
                        toast.success('Тест голоса запущен');
                      } else {
                        toast.error('Голос не поддерживается браузером');
                      }
                    }}
                    className="border-[#6C63FF] text-[#6C63FF]"
                  >
                    <Volume2 className="w-4 h-4 mr-2" />
                    Тест голоса
                  </Button>
                </>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
