import { create } from 'zustand';
import { persist } from 'zustand/middleware';

// ==================== ТИПЫ ДАННЫХ ====================

// KPI карточки
export interface KpiCard {
  title: string;
  value: string;
  change?: number;
  icon: string;
  color: 'green' | 'red' | 'neutral';
}

// Лента активности
export interface ActivityItem {
  id: string;
  type: 'comment' | 'ban' | 'join' | 'warning' | 'limit' | 'success' | 'error' | 'info';
  message: string;
  timestamp: Date | string;
  campaignId?: string;
  accountId?: string;
}

// Кампании
export interface Campaign {
  id: string;
  name: string;
  status: 'active' | 'paused' | 'error' | 'draft';
  offerType: 'casino' | 'crypto' | 'dating' | 'nutra';
  accountsActive: number;
  accountsTotal: number;
  commentsToday: number;
  revenue: number;
  budget: number;
  budgetSpent: number;
  link?: string;
  autoReplaceOnBan?: boolean;
  maxCommentsPerAccount?: number;
  postingMode?: 'new' | 'old' | 'both';
  delayMin?: number;
  delayMax?: number;
  delayRandom?: boolean;
  useUniqueText?: boolean;
  useDeepSeek?: boolean;
  deepSeekTemperature?: number;
  maxCostPerLead?: number;
  workTimeStart?: string;
  workTimeEnd?: string;
  createdAt: Date | string;
  updatedAt: Date | string;
}

// Аккаунты
export interface Account {
  id: string;
  platform: string;
  username?: string;
  phone?: string;
  proxy?: string;
  commentsToday: number;
  commentsTotal: number;
  banRisk: number;
  status: 'active' | 'limit' | 'banned' | 'new';
  warmingProgress: number;
  dailyComments: number;
  dailyDm: number;
  maxComments: number;
  maxDm: number;
  lastUsedAt?: Date | string;
  createdAt?: Date | string;
}

// Настройки приложения
export interface AppSettings {
  deepseekApiKey: string;
  telegramApiId: string;
  telegramApiHash: string;
  proxyServiceUrl?: string;
  maxCommentsPerAccount: number;
  delayMin: number;
  delayMax: number;
  delayRandom: boolean;
  autoPauseOnCpa: boolean;
  telegramChatId?: string;
  riskAssistantEnabled: boolean;
  riskThreshold: 'low' | 'medium' | 'high';
  autoGenerateDisclaimers: boolean;
  logWarnings: boolean;
}

// Аналитика
export interface AnalyticsData {
  date: string;
  revenue: number;
  comments: number;
  bans: number;
  conversions: number;
}

export interface TopChannel {
  id: string;
  name: string;
  comments: number;
  clicks: number;
  conversion: number;
  revenue: number;
}

export interface TopComment {
  id: string;
  text: string;
  ctr: number;
  conversion: number;
}

// Инфлюенсеры
export interface Influencer {
  id: string;
  name: string;
  platform?: string;
  niche?: string;
  subscribers?: number;
  engagement?: number;
  avatar?: string;
  createdAt?: Date | string;
  // Дополнительные поля из Prisma схемы
  age?: number;
  gender?: string;
  role?: string;
  style?: string;
  country?: string;
  language?: string;
  avatarUrl?: string;
  photos?: string;
  voiceProvider?: string;
  voiceId?: string;
  status?: string;
  telegramUsername?: string;
  telegramChannel?: string;
  instagramUsername?: string;
  tiktokUsername?: string;
  youtubeChannelId?: string;
  postPrompt?: string;
  commentPrompt?: string;
  dmPrompt?: string;
  storyPrompt?: string;
  greetingPrompt?: string;
  tone?: string;
  phrases?: string;
  forbidden?: string;
  personality?: string;
  interests?: string;
  bio?: string;
  accountId?: string;
  simCardId?: string;
  postsCount?: number;
  leadsCount?: number;
  revenue?: number;
  banRisk?: number;
  predictedLifeDays?: number;
}

// Офферы
export interface Offer {
  id: string;
  name: string;
  status: 'active' | 'paused' | 'draft';
  affiliateLink?: string;
  payout?: number;
  currency?: string;
  clicks?: number;
  leads?: number;
  revenue?: number;
  createdAt?: Date | string;
}

// SIM-карты
export interface SimCard {
  id: string;
  phoneNumber: string;
  operator: string;
  country: string;
  status: 'active' | 'inactive' | 'blocked';
  balance?: number;
  expiryDate?: Date | string;
  createdAt?: Date | string;
}

// Уведомления
export interface Notification {
  id: string;
  type: 'warning' | 'error' | 'success' | 'info';
  title: string;
  message: string;
  isRead: boolean;
  createdAt: string;
}

// ==================== СОСТОЯНИЕ ПРИЛОЖЕНИЯ ====================

interface AppState {
  // Навигация
  activeTab: string;
  setActiveTab: (tab: string) => void;
  
  // KPI данные
  kpiData: KpiCard[];
  setKpiData: (data: KpiCard[]) => void;
  
  // Лента активности
  activities: ActivityItem[];
  setActivities: (activities: ActivityItem[]) => void;
  addActivity: (activity: ActivityItem) => void;
  
  // Кампании
  campaigns: Campaign[];
  setCampaigns: (campaigns: Campaign[]) => void;
  addCampaign: (campaign: Campaign) => void;
  updateCampaign: (id: string, data: Partial<Campaign>) => void;
  removeCampaign: (id: string) => void;
  selectedCampaign: Campaign | null;
  selectCampaign: (campaign: Campaign | null) => void;
  campaignModalOpen: boolean;
  setCampaignModalOpen: (open: boolean) => void;
  editingCampaign: Campaign | null;
  setEditingCampaign: (campaign: Campaign | null) => void;
  
  // Аккаунты
  accounts: Account[];
  setAccounts: (accounts: Account[]) => void;
  addAccount: (account: Account) => void;
  updateAccount: (id: string, data: Partial<Account>) => void;
  removeAccount: (id: string) => void;
  selectedAccounts: string[];
  setSelectedAccounts: (ids: string[]) => void;
  accountModalOpen: boolean;
  setAccountModalOpen: (open: boolean) => void;
  
  // Инфлюенсеры
  influencers: Influencer[];
  setInfluencers: (influencers: Influencer[]) => void;
  addInfluencer: (influencer: Influencer) => void;
  updateInfluencer: (id: string, data: Partial<Influencer>) => void;
  removeInfluencer: (id: string) => void;
  createInfluencerOpen: boolean;
  setCreateInfluencerOpen: (open: boolean) => void;
  editingInfluencer: Influencer | null;
  setEditingInfluencer: (influencer: Influencer | null) => void;
  
  // Офферы
  offers: Offer[];
  setOffers: (offers: Offer[]) => void;
  addOffer: (offer: Offer) => void;
  updateOffer: (id: string, data: Partial<Offer>) => void;
  removeOffer: (id: string) => void;
  
  // SIM-карты
  simCards: SimCard[];
  setSimCards: (simCards: SimCard[]) => void;
  addSimCard: (simCard: SimCard) => void;
  updateSimCard: (id: string, data: Partial<SimCard>) => void;
  removeSimCard: (id: string) => void;
  
  // Аналитика
  analyticsData: AnalyticsData[];
  setAnalyticsData: (data: AnalyticsData[]) => void;
  topChannels: TopChannel[];
  setTopChannels: (channels: TopChannel[]) => void;
  topComments: TopComment[];
  setTopComments: (comments: TopComment[]) => void;
  analyticsPeriod: 'today' | 'week' | 'month' | 'custom';
  setAnalyticsPeriod: (period: 'today' | 'week' | 'month' | 'custom') => void;
  analyticsChartType: 'revenue' | 'comments' | 'conversion';
  setAnalyticsChartType: (type: 'revenue' | 'comments' | 'conversion') => void;
  
  // Настройки
  settings: AppSettings;
  updateSettings: (settings: Partial<AppSettings>) => void;
  settingsOpen: boolean;
  setSettingsOpen: (open: boolean) => void;
  
  // Уведомления
  notifications: Notification[];
  addNotification: (notification: Notification) => void;
  markNotificationRead: (id: string) => void;
  clearNotifications: () => void;
  
  // Загрузка
  isLoading: boolean;
  setIsLoading: (loading: boolean) => void;
  
  // Ошибки
  error: string | null;
  setError: (error: string | null) => void;
  
  // Real-time
  isConnected: boolean;
  setConnected: (connected: boolean) => void;
}

export const useAppStore = create<AppState>()(
  persist(
    (set, get) => ({
      // Навигация
      activeTab: 'dashboard',
      setActiveTab: (tab) => set({ activeTab: tab }),
      
      // KPI данные
      kpiData: [],
      setKpiData: (kpiData) => set({ kpiData }),
      
      // Лента активности
      activities: [],
      setActivities: (activities) => set({ activities }),
      addActivity: (activity) => set((state) => ({
        activities: [activity, ...state.activities].slice(0, 100)
      })),
      
      // Кампании
      campaigns: [],
      setCampaigns: (campaigns) => set({ campaigns }),
      addCampaign: (campaign) => set((state) => ({
        campaigns: [campaign, ...state.campaigns]
      })),
      updateCampaign: (id, data) => set((state) => ({
        campaigns: state.campaigns.map((c) =>
          c.id === id ? { ...c, ...data } : c
        )
      })),
      removeCampaign: (id) => set((state) => ({
        campaigns: state.campaigns.filter((c) => c.id !== id)
      })),
      selectedCampaign: null,
      selectCampaign: (campaign) => set({ selectedCampaign: campaign }),
      campaignModalOpen: false,
      setCampaignModalOpen: (open) => set({ campaignModalOpen: open }),
      editingCampaign: null,
      setEditingCampaign: (campaign) => set({ editingCampaign: campaign }),
      
      // Аккаунты
      accounts: [],
      setAccounts: (accounts) => set({ accounts }),
      addAccount: (account) => set((state) => ({
        accounts: [account, ...state.accounts]
      })),
      updateAccount: (id, data) => set((state) => ({
        accounts: state.accounts.map((a) =>
          a.id === id ? { ...a, ...data } : a
        )
      })),
      removeAccount: (id) => set((state) => ({
        accounts: state.accounts.filter((a) => a.id !== id)
      })),
      selectedAccounts: [],
      setSelectedAccounts: (ids) => set({ selectedAccounts: ids }),
      accountModalOpen: false,
      setAccountModalOpen: (open) => set({ accountModalOpen: open }),
      
      // Инфлюенсеры
      influencers: [],
      setInfluencers: (influencers) => set({ influencers }),
      addInfluencer: (influencer) => set((state) => ({
        influencers: [influencer, ...state.influencers]
      })),
      updateInfluencer: (id, data) => set((state) => ({
        influencers: state.influencers.map((i) =>
          i.id === id ? { ...i, ...data } : i
        )
      })),
      removeInfluencer: (id) => set((state) => ({
        influencers: state.influencers.filter((i) => i.id !== id)
      })),
      createInfluencerOpen: false,
      setCreateInfluencerOpen: (open) => set({ createInfluencerOpen: open }),
      editingInfluencer: null,
      setEditingInfluencer: (influencer) => set({ editingInfluencer: influencer }),
      
      // Офферы
      offers: [],
      setOffers: (offers) => set({ offers }),
      addOffer: (offer) => set((state) => ({
        offers: [offer, ...state.offers]
      })),
      updateOffer: (id, data) => set((state) => ({
        offers: state.offers.map((o) =>
          o.id === id ? { ...o, ...data } : o
        )
      })),
      removeOffer: (id) => set((state) => ({
        offers: state.offers.filter((o) => o.id !== id)
      })),
      
      // SIM-карты
      simCards: [],
      setSimCards: (simCards) => set({ simCards }),
      addSimCard: (simCard) => set((state) => ({
        simCards: [simCard, ...state.simCards]
      })),
      updateSimCard: (id, data) => set((state) => ({
        simCards: state.simCards.map((s) =>
          s.id === id ? { ...s, ...data } : s
        )
      })),
      removeSimCard: (id) => set((state) => ({
        simCards: state.simCards.filter((s) => s.id !== id)
      })),
      
      // Аналитика
      analyticsData: [],
      setAnalyticsData: (analyticsData) => set({ analyticsData }),
      topChannels: [],
      setTopChannels: (topChannels) => set({ topChannels }),
      topComments: [],
      setTopComments: (topComments) => set({ topComments }),
      analyticsPeriod: 'week',
      setAnalyticsPeriod: (analyticsPeriod) => set({ analyticsPeriod }),
      analyticsChartType: 'revenue',
      setAnalyticsChartType: (analyticsChartType) => set({ analyticsChartType }),
      
      // Настройки
      settings: {
        deepseekApiKey: '',
        telegramApiId: '',
        telegramApiHash: '',
        maxCommentsPerAccount: 50,
        delayMin: 30,
        delayMax: 120,
        delayRandom: true,
        autoPauseOnCpa: false,
        riskAssistantEnabled: true,
        riskThreshold: 'medium',
        autoGenerateDisclaimers: true,
        logWarnings: true,
      },
      updateSettings: (newSettings) => set((state) => ({
        settings: { ...state.settings, ...newSettings }
      })),
      settingsOpen: false,
      setSettingsOpen: (open) => set({ settingsOpen: open }),
      
      // Уведомления
      notifications: [],
      addNotification: (notification) => set((state) => ({
        notifications: [notification, ...state.notifications].slice(0, 100)
      })),
      markNotificationRead: (id) => set((state) => ({
        notifications: state.notifications.map((n) =>
          n.id === id ? { ...n, isRead: true } : n
        )
      })),
      clearNotifications: () => set({ notifications: [] }),
      
      // Загрузка
      isLoading: false,
      setIsLoading: (loading) => set({ isLoading: loading }),
      
      // Ошибки
      error: null,
      setError: (error) => set({ error }),
      
      // Real-time
      isConnected: false,
      setConnected: (connected) => set({ isConnected: connected }),
    }),
    {
      name: 'mukn-traffic-store-v2',
      partialize: (state) => ({
        activeTab: state.activeTab,
        settings: state.settings,
        notifications: state.notifications,
      }),
    }
  )
);
