// Monetization Schemes Library - 200+ schemes for МУКН platform
// Categories: CPA, Affiliate, Farming, Direct Sales, Arbitrage

export type SchemeCategory = 'cpa' | 'affiliate' | 'farming' | 'direct' | 'arbitrage';
export type RiskLevel = 'low' | 'medium' | 'high' | 'extreme';
export type Platform = 'telegram' | 'instagram' | 'tiktok' | 'twitter' | 'youtube' | 'discord' | 'facebook' | 'reddit' | 'whatsapp' | 'all';

export interface MonetizationSchemeDefinition {
  id: string;
  name: string;
  description: string;
  category: SchemeCategory;
  platforms: Platform[];
  expectedRevenue: string;
  riskLevel: RiskLevel;
  automationLevel: number;
  isFree: boolean;
  minAccounts: number;
  minWarmingDays: number;
  timeToProfit: number;
  requirements?: Record<string, unknown>;
  config?: Record<string, unknown>;
  instructions?: string[];
}

export const MONETIZATION_SCHEMES: MonetizationSchemeDefinition[] = [
  // ==================== CPA SCHEMES (50) ====================
  {
    id: 'cpa-1',
    name: 'Telegram Casino Comments',
    description: 'Post casino affiliate links in Telegram channels with warmed accounts',
    category: 'cpa',
    platforms: ['telegram'],
    expectedRevenue: '$50-100/mo',
    riskLevel: 'low',
    automationLevel: 100,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 7,
    requirements: { proxy: 'recommended', warmedAccounts: 3 },
    instructions: ['Find crypto/casino channels', 'Post comments with affiliate links', 'Rotate accounts daily']
  },
  {
    id: 'cpa-2',
    name: 'Instagram Reels CPA',
    description: 'Promote CPA offers through Instagram Reels comments',
    category: 'cpa',
    platforms: ['instagram'],
    expectedRevenue: '$30-80/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 10,
    requirements: { proxy: 'required', warmedAccounts: 5 }
  },
  {
    id: 'cpa-3',
    name: 'TikTok Comment Marketing',
    description: 'Comment CPA offers on trending TikTok videos',
    category: 'cpa',
    platforms: ['tiktok'],
    expectedRevenue: '$40-120/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 21,
    timeToProfit: 14,
    requirements: { proxy: 'required', warmedAccounts: 5 }
  },
  {
    id: 'cpa-4',
    name: 'Twitter Crypto Shilling',
    description: 'Promote crypto projects through Twitter replies',
    category: 'cpa',
    platforms: ['twitter'],
    expectedRevenue: '$60-150/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 5,
    requirements: { proxy: 'recommended' }
  },
  {
    id: 'cpa-5',
    name: 'YouTube Comment CPA',
    description: 'Post CPA links in YouTube comments under relevant videos',
    category: 'cpa',
    platforms: ['youtube'],
    expectedRevenue: '$25-60/mo',
    riskLevel: 'low',
    automationLevel: 90,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 7,
    timeToProfit: 7
  },
  {
    id: 'cpa-6',
    name: 'Discord Server Promotion',
    description: 'Promote CPA offers in Discord servers',
    category: 'cpa',
    platforms: ['discord'],
    expectedRevenue: '$30-90/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'cpa-7',
    name: 'Reddit Affiliate Posting',
    description: 'Post affiliate links in relevant subreddits',
    category: 'cpa',
    platforms: ['reddit'],
    expectedRevenue: '$20-70/mo',
    riskLevel: 'medium',
    automationLevel: 60,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 14,
    timeToProfit: 10
  },
  {
    id: 'cpa-8',
    name: 'Facebook Group Marketing',
    description: 'Promote CPA offers in Facebook groups',
    category: 'cpa',
    platforms: ['facebook'],
    expectedRevenue: '$35-95/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 14,
    timeToProfit: 10
  },
  {
    id: 'cpa-9',
    name: 'WhatsApp Broadcast CPA',
    description: 'Send CPA offers via WhatsApp broadcast lists',
    category: 'cpa',
    platforms: ['whatsapp'],
    expectedRevenue: '$40-100/mo',
    riskLevel: 'medium',
    automationLevel: 65,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 7,
    timeToProfit: 5
  },
  {
    id: 'cpa-10',
    name: 'Multi-Platform Casino Push',
    description: 'Cross-platform casino CPA promotion',
    category: 'cpa',
    platforms: ['telegram', 'instagram', 'twitter'],
    expectedRevenue: '$100-300/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 14,
    timeToProfit: 7
  },
  {
    id: 'cpa-11',
    name: 'Nutra Offers Instagram',
    description: 'Promote health/beauty CPA offers on Instagram',
    category: 'cpa',
    platforms: ['instagram'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'cpa-12',
    name: 'Dating App CPA',
    description: 'Promote dating CPA offers on social platforms',
    category: 'cpa',
    platforms: ['instagram', 'tiktok'],
    expectedRevenue: '$60-180/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 10
  },
  {
    id: 'cpa-13',
    name: 'Gambling Stream CPA',
    description: 'Promote gambling offers via Telegram streams',
    category: 'cpa',
    platforms: ['telegram'],
    expectedRevenue: '$80-250/mo',
    riskLevel: 'medium',
    automationLevel: 80,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 7
  },
  {
    id: 'cpa-14',
    name: 'Crypto Airdrop CPA',
    description: 'Promote crypto airdrop offers',
    category: 'cpa',
    platforms: ['telegram', 'twitter'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 90,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'cpa-15',
    name: 'Sweepstakes CPA',
    description: 'Promote sweepstakes and giveaway offers',
    category: 'cpa',
    platforms: ['instagram', 'facebook'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 7
  },
  {
    id: 'cpa-16',
    name: 'Mobile App Installs',
    description: 'Promote mobile app install offers',
    category: 'cpa',
    platforms: ['instagram', 'tiktok', 'youtube'],
    expectedRevenue: '$50-150/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 7,
    timeToProfit: 5
  },
  {
    id: 'cpa-17',
    name: 'Finance Offers Twitter',
    description: 'Promote finance/trading CPA offers on Twitter',
    category: 'cpa',
    platforms: ['twitter'],
    expectedRevenue: '$70-200/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 7
  },
  {
    id: 'cpa-18',
    name: 'E-commerce Discount CPA',
    description: 'Promote e-commerce discount offers',
    category: 'cpa',
    platforms: ['telegram', 'instagram'],
    expectedRevenue: '$40-120/mo',
    riskLevel: 'low',
    automationLevel: 90,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'cpa-19',
    name: 'VPN Service CPA',
    description: 'Promote VPN subscription offers',
    category: 'cpa',
    platforms: ['telegram', 'twitter', 'reddit'],
    expectedRevenue: '$30-90/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'cpa-20',
    name: 'Software Trial CPA',
    description: 'Promote software trial offers',
    category: 'cpa',
    platforms: ['telegram', 'discord'],
    expectedRevenue: '$25-80/mo',
    riskLevel: 'low',
    automationLevel: 90,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'cpa-21',
    name: 'Betting Tips Telegram',
    description: 'Share betting tips with affiliate links',
    category: 'cpa',
    platforms: ['telegram'],
    expectedRevenue: '$60-180/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 7
  },
  {
    id: 'cpa-22',
    name: 'Forex Trading CPA',
    description: 'Promote forex broker offers',
    category: 'cpa',
    platforms: ['telegram', 'instagram'],
    expectedRevenue: '$100-400/mo',
    riskLevel: 'medium',
    automationLevel: 75,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'cpa-23',
    name: 'Credit Card CPA',
    description: 'Promote credit card offers',
    category: 'cpa',
    platforms: ['facebook', 'instagram'],
    expectedRevenue: '$50-150/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'cpa-24',
    name: 'Insurance Leads CPA',
    description: 'Generate insurance lead submissions',
    category: 'cpa',
    platforms: ['facebook'],
    expectedRevenue: '$80-250/mo',
    riskLevel: 'medium',
    automationLevel: 65,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'cpa-25',
    name: 'Education Course CPA',
    description: 'Promote online education courses',
    category: 'cpa',
    platforms: ['instagram', 'youtube', 'telegram'],
    expectedRevenue: '$40-120/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'cpa-26',
    name: 'Gaming Niche CPA',
    description: 'Promote gaming-related CPA offers',
    category: 'cpa',
    platforms: ['discord', 'telegram', 'youtube'],
    expectedRevenue: '$50-150/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'cpa-27',
    name: 'Adult CPA Telegram',
    description: 'Adult content CPA promotion',
    category: 'cpa',
    platforms: ['telegram'],
    expectedRevenue: '$100-300/mo',
    riskLevel: 'high',
    automationLevel: 90,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 7,
    timeToProfit: 5
  },
  {
    id: 'cpa-28',
    name: 'Streaming Service CPA',
    description: 'Promote streaming subscriptions',
    category: 'cpa',
    platforms: ['telegram', 'instagram'],
    expectedRevenue: '$30-80/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'cpa-29',
    name: 'Web Hosting CPA',
    description: 'Promote web hosting offers',
    category: 'cpa',
    platforms: ['telegram', 'twitter', 'reddit'],
    expectedRevenue: '$40-100/mo',
    riskLevel: 'low',
    automationLevel: 90,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'cpa-30',
    name: 'Travel Booking CPA',
    description: 'Promote travel booking offers',
    category: 'cpa',
    platforms: ['instagram', 'facebook'],
    expectedRevenue: '$50-150/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'cpa-31',
    name: 'Sports Betting CPA',
    description: 'Promote sports betting platforms',
    category: 'cpa',
    platforms: ['telegram', 'twitter'],
    expectedRevenue: '$80-250/mo',
    riskLevel: 'medium',
    automationLevel: 80,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 7,
    timeToProfit: 7
  },
  {
    id: 'cpa-32',
    name: 'Pet Supplies CPA',
    description: 'Promote pet supplies affiliate offers',
    category: 'cpa',
    platforms: ['instagram', 'tiktok'],
    expectedRevenue: '$25-70/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'cpa-33',
    name: 'Home Decor CPA',
    description: 'Promote home decoration offers',
    category: 'cpa',
    platforms: ['instagram', 'pinterest'],
    expectedRevenue: '$30-90/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'cpa-34',
    name: 'Auto Insurance CPA',
    description: 'Generate auto insurance leads',
    category: 'cpa',
    platforms: ['facebook'],
    expectedRevenue: '$70-200/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'cpa-35',
    name: 'Crypto Exchange CPA',
    description: 'Promote crypto exchange signups',
    category: 'cpa',
    platforms: ['telegram', 'twitter'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'low',
    automationLevel: 90,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'cpa-36',
    name: 'Personal Loan CPA',
    description: 'Promote personal loan offers',
    category: 'cpa',
    platforms: ['facebook', 'instagram'],
    expectedRevenue: '$60-180/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'cpa-37',
    name: 'Solar Panel CPA',
    description: 'Generate solar installation leads',
    category: 'cpa',
    platforms: ['facebook'],
    expectedRevenue: '$100-500/mo',
    riskLevel: 'low',
    automationLevel: 60,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 7,
    timeToProfit: 14
  },
  {
    id: 'cpa-38',
    name: 'Weight Loss CPA',
    description: 'Promote weight loss offers',
    category: 'cpa',
    platforms: ['instagram', 'tiktok'],
    expectedRevenue: '$60-200/mo',
    riskLevel: 'medium',
    automationLevel: 75,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'cpa-39',
    name: 'Skin Care CPA',
    description: 'Promote skin care CPA offers',
    category: 'cpa',
    platforms: ['instagram', 'tiktok'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 10,
    timeToProfit: 10
  },
  {
    id: 'cpa-40',
    name: 'Muscle Building CPA',
    description: 'Promote fitness/muscle building offers',
    category: 'cpa',
    platforms: ['instagram', 'youtube'],
    expectedRevenue: '$50-150/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 10,
    timeToProfit: 10
  },
  {
    id: 'cpa-41',
    name: 'Mental Health CPA',
    description: 'Promote mental health service offers',
    category: 'cpa',
    platforms: ['instagram', 'tiktok'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 10,
    timeToProfit: 10
  },
  {
    id: 'cpa-42',
    name: 'CBD Products CPA',
    description: 'Promote CBD product offers',
    category: 'cpa',
    platforms: ['instagram', 'facebook'],
    expectedRevenue: '$50-150/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 10,
    timeToProfit: 10
  },
  {
    id: 'cpa-43',
    name: 'Language Learning CPA',
    description: 'Promote language learning apps',
    category: 'cpa',
    platforms: ['instagram', 'youtube', 'tiktok'],
    expectedRevenue: '$30-90/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'cpa-44',
    name: 'Stock Trading CPA',
    description: 'Promote stock trading platforms',
    category: 'cpa',
    platforms: ['telegram', 'twitter', 'youtube'],
    expectedRevenue: '$60-200/mo',
    riskLevel: 'medium',
    automationLevel: 80,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 7
  },
  {
    id: 'cpa-45',
    name: 'Real Estate CPA',
    description: 'Generate real estate leads',
    category: 'cpa',
    platforms: ['facebook', 'instagram'],
    expectedRevenue: '$80-300/mo',
    riskLevel: 'low',
    automationLevel: 60,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'cpa-46',
    name: 'Tech Gadgets CPA',
    description: 'Promote tech gadget offers',
    category: 'cpa',
    platforms: ['telegram', 'youtube', 'twitter'],
    expectedRevenue: '$40-120/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'cpa-47',
    name: 'Fashion Affiliate CPA',
    description: 'Promote fashion/clothing offers',
    category: 'cpa',
    platforms: ['instagram', 'tiktok'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'cpa-48',
    name: 'Pet Insurance CPA',
    description: 'Promote pet insurance offers',
    category: 'cpa',
    platforms: ['facebook', 'instagram'],
    expectedRevenue: '$40-120/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 10,
    timeToProfit: 10
  },
  {
    id: 'cpa-49',
    name: 'Subscription Box CPA',
    description: 'Promote subscription box services',
    category: 'cpa',
    platforms: ['instagram', 'tiktok'],
    expectedRevenue: '$25-80/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 7,
    timeToProfit: 7
  },
  {
    id: 'cpa-50',
    name: 'NFT Minting CPA',
    description: 'Promote NFT minting campaigns',
    category: 'cpa',
    platforms: ['telegram', 'twitter'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'high',
    automationLevel: 85,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 5,
    timeToProfit: 5
  },

  // ==================== AFFILIATE SCHEMES (50) ====================
  {
    id: 'aff-1',
    name: 'Crypto Referral Links',
    description: 'Share crypto platform referral links',
    category: 'affiliate',
    platforms: ['telegram', 'twitter'],
    expectedRevenue: '$100-500/mo',
    riskLevel: 'medium',
    automationLevel: 90,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 7
  },
  {
    id: 'aff-2',
    name: 'Amazon Affiliate Program',
    description: 'Promote Amazon products for commission',
    category: 'affiliate',
    platforms: ['instagram', 'youtube', 'tiktok'],
    expectedRevenue: '$50-300/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 10,
    timeToProfit: 14
  },
  {
    id: 'aff-3',
    name: 'ClickBank Products',
    description: 'Promote ClickBank digital products',
    category: 'affiliate',
    platforms: ['instagram', 'telegram', 'facebook'],
    expectedRevenue: '$60-400/mo',
    riskLevel: 'medium',
    automationLevel: 75,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 10,
    timeToProfit: 10
  },
  {
    id: 'aff-4',
    name: 'ShareASale Products',
    description: 'Promote ShareASale affiliate products',
    category: 'affiliate',
    platforms: ['instagram', 'twitter'],
    expectedRevenue: '$40-200/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'aff-5',
    name: 'CJ Affiliate Marketing',
    description: 'Promote CJ affiliate network offers',
    category: 'affiliate',
    platforms: ['instagram', 'facebook'],
    expectedRevenue: '$50-250/mo',
    riskLevel: 'low',
    automationLevel: 65,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 10,
    timeToProfit: 14
  },
  {
    id: 'aff-6',
    name: 'eBay Partner Network',
    description: 'Promote eBay products',
    category: 'affiliate',
    platforms: ['instagram', 'youtube'],
    expectedRevenue: '$30-150/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'aff-7',
    name: 'Rakuten Marketing',
    description: 'Promote Rakuten affiliate offers',
    category: 'affiliate',
    platforms: ['instagram', 'facebook', 'twitter'],
    expectedRevenue: '$40-180/mo',
    riskLevel: 'low',
    automationLevel: 65,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 10,
    timeToProfit: 14
  },
  {
    id: 'aff-8',
    name: 'Impact Affiliate',
    description: 'Promote Impact network offers',
    category: 'affiliate',
    platforms: ['instagram', 'telegram'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'aff-9',
    name: 'Awin Affiliate Network',
    description: 'Promote Awin affiliate products',
    category: 'affiliate',
    platforms: ['instagram', 'facebook'],
    expectedRevenue: '$35-150/mo',
    riskLevel: 'low',
    automationLevel: 65,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 10,
    timeToProfit: 14
  },
  {
    id: 'aff-10',
    name: 'FlexOffers Program',
    description: 'Promote FlexOffers products',
    category: 'affiliate',
    platforms: ['instagram', 'twitter'],
    expectedRevenue: '$30-120/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'aff-11',
    name: 'MaxBounty Offers',
    description: 'Promote MaxBounty CPA offers',
    category: 'affiliate',
    platforms: ['telegram', 'instagram'],
    expectedRevenue: '$80-400/mo',
    riskLevel: 'medium',
    automationLevel: 80,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 10,
    timeToProfit: 7
  },
  {
    id: 'aff-12',
    name: 'PeerFly Affiliate',
    description: 'Promote PeerFly CPA offers',
    category: 'affiliate',
    platforms: ['telegram', 'instagram'],
    expectedRevenue: '$60-300/mo',
    riskLevel: 'medium',
    automationLevel: 80,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 10,
    timeToProfit: 7
  },
  {
    id: 'aff-13',
    name: 'CPAGrip Network',
    description: 'Promote CPAGrip offers',
    category: 'affiliate',
    platforms: ['telegram', 'instagram', 'facebook'],
    expectedRevenue: '$50-250/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 5
  },
  {
    id: 'aff-14',
    name: 'AdWork Media',
    description: 'Promote AdWork Media offers',
    category: 'affiliate',
    platforms: ['telegram', 'instagram'],
    expectedRevenue: '$40-200/mo',
    riskLevel: 'medium',
    automationLevel: 80,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 7
  },
  {
    id: 'aff-15',
    name: 'ConvertKit Affiliate',
    description: 'Promote email marketing tools',
    category: 'affiliate',
    platforms: ['twitter', 'youtube', 'telegram'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-16',
    name: 'Shopify Affiliate',
    description: 'Promote Shopify e-commerce platform',
    category: 'affiliate',
    platforms: ['youtube', 'instagram', 'telegram'],
    expectedRevenue: '$100-500/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 10,
    timeToProfit: 14
  },
  {
    id: 'aff-17',
    name: 'Bluehost Affiliate',
    description: 'Promote web hosting services',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-18',
    name: 'Canva Affiliate',
    description: 'Promote Canva design tool',
    category: 'affiliate',
    platforms: ['instagram', 'youtube', 'tiktok'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-19',
    name: 'Semrush Affiliate',
    description: 'Promote SEO tools',
    category: 'affiliate',
    platforms: ['telegram', 'twitter', 'youtube'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-20',
    name: 'Fiverr Affiliate',
    description: 'Promote Fiverr freelance services',
    category: 'affiliate',
    platforms: ['instagram', 'telegram', 'youtube'],
    expectedRevenue: '$30-150/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-21',
    name: 'Udemy Affiliate',
    description: 'Promote online courses',
    category: 'affiliate',
    platforms: ['instagram', 'telegram', 'youtube'],
    expectedRevenue: '$25-100/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-22',
    name: 'Coursera Affiliate',
    description: 'Promote Coursera courses',
    category: 'affiliate',
    platforms: ['instagram', 'youtube', 'telegram'],
    expectedRevenue: '$30-120/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-23',
    name: 'Skillshare Affiliate',
    description: 'Promote Skillshare membership',
    category: 'affiliate',
    platforms: ['instagram', 'youtube', 'tiktok'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-24',
    name: 'Leadpages Affiliate',
    description: 'Promote landing page builder',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-25',
    name: 'Teachable Affiliate',
    description: 'Promote online course platform',
    category: 'affiliate',
    platforms: ['youtube', 'instagram', 'telegram'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 10
  },
  {
    id: 'aff-26',
    name: 'Hostinger Affiliate',
    description: 'Promote web hosting',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-27',
    name: 'Wix Affiliate Program',
    description: 'Promote website builder',
    category: 'affiliate',
    platforms: ['youtube', 'instagram', 'telegram'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-28',
    name: 'Squarespace Affiliate',
    description: 'Promote website builder',
    category: 'affiliate',
    platforms: ['youtube', 'instagram'],
    expectedRevenue: '$50-180/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 10
  },
  {
    id: 'aff-29',
    name: 'GetResponse Affiliate',
    description: 'Promote email marketing platform',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-30',
    name: 'AWeber Affiliate',
    description: 'Promote email marketing service',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-31',
    name: 'Kajabi Affiliate',
    description: 'Promote online business platform',
    category: 'affiliate',
    platforms: ['youtube', 'instagram', 'telegram'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 10
  },
  {
    id: 'aff-32',
    name: 'Thinkific Affiliate',
    description: 'Promote course creation platform',
    category: 'affiliate',
    platforms: ['youtube', 'instagram', 'telegram'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 10
  },
  {
    id: 'aff-33',
    name: 'Podia Affiliate',
    description: 'Promote digital product platform',
    category: 'affiliate',
    platforms: ['youtube', 'instagram', 'telegram'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-34',
    name: 'Notion Affiliate',
    description: 'Promote productivity tool',
    category: 'affiliate',
    platforms: ['twitter', 'youtube', 'telegram'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'aff-35',
    name: 'Airtable Affiliate',
    description: 'Promote database tool',
    category: 'affiliate',
    platforms: ['twitter', 'youtube', 'telegram'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'aff-36',
    name: 'Zapier Affiliate',
    description: 'Promote automation tool',
    category: 'affiliate',
    platforms: ['twitter', 'youtube', 'telegram'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'aff-37',
    name: 'Webflow Affiliate',
    description: 'Promote web design tool',
    category: 'affiliate',
    platforms: ['youtube', 'instagram', 'telegram'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 10
  },
  {
    id: 'aff-38',
    name: 'Elementor Affiliate',
    description: 'Promote WordPress builder',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-39',
    name: 'HubSpot Affiliate',
    description: 'Promote CRM platform',
    category: 'affiliate',
    platforms: ['youtube', 'twitter', 'telegram'],
    expectedRevenue: '$50-250/mo',
    riskLevel: 'low',
    automationLevel: 65,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 14
  },
  {
    id: 'aff-40',
    name: 'Monday.com Affiliate',
    description: 'Promote project management tool',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 10
  },
  {
    id: 'aff-41',
    name: 'Asana Affiliate',
    description: 'Promote project management tool',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'aff-42',
    name: 'Slack Affiliate',
    description: 'Promote team communication tool',
    category: 'affiliate',
    platforms: ['twitter', 'telegram', 'youtube'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'aff-43',
    name: 'Zoom Affiliate',
    description: 'Promote video conferencing tool',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'aff-44',
    name: 'Dropbox Affiliate',
    description: 'Promote cloud storage service',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'aff-45',
    name: 'LastPass Affiliate',
    description: 'Promote password manager',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$15-50/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'aff-46',
    name: 'Grammarly Affiliate',
    description: 'Promote writing assistant tool',
    category: 'affiliate',
    platforms: ['youtube', 'instagram', 'telegram'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'aff-47',
    name: ' NordVPN Affiliate',
    description: 'Promote VPN service',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'aff-48',
    name: 'ExpressVPN Affiliate',
    description: 'Promote VPN service',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'aff-49',
    name: 'Surfshark Affiliate',
    description: 'Promote VPN service',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$35-120/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },
  {
    id: 'aff-50',
    name: 'CyberGhost Affiliate',
    description: 'Promote VPN service',
    category: 'affiliate',
    platforms: ['youtube', 'telegram', 'twitter'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 2,
    minWarmingDays: 5,
    timeToProfit: 5
  },

  // ==================== FARMING SCHEMES (40) ====================
  {
    id: 'farm-1',
    name: 'Airdrop Farming',
    description: 'Farm crypto airdrops with multiple accounts',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'medium',
    automationLevel: 90,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 14
  },
  {
    id: 'farm-2',
    name: 'Telegram Mini Games',
    description: 'Farm Telegram mini game rewards',
    category: 'farming',
    platforms: ['telegram'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 100,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 3,
    timeToProfit: 7
  },
  {
    id: 'farm-3',
    name: 'Discord Nitro Farming',
    description: 'Farm Discord Nitro through various methods',
    category: 'farming',
    platforms: ['discord'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'medium',
    automationLevel: 80,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 7,
    timeToProfit: 14
  },
  {
    id: 'farm-4',
    name: 'Twitter Engagement Farm',
    description: 'Farm Twitter engagement for monetization',
    category: 'farming',
    platforms: ['twitter'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'farm-5',
    name: 'Instagram Engagement Pods',
    description: 'Farm Instagram engagement in pods',
    category: 'farming',
    platforms: ['instagram'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'farm-6',
    name: 'TikTok View Farming',
    description: 'Farm TikTok views and engagement',
    category: 'farming',
    platforms: ['tiktok'],
    expectedRevenue: '$40-120/mo',
    riskLevel: 'medium',
    automationLevel: 75,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'farm-7',
    name: 'YouTube Sub Farming',
    description: 'Farm YouTube subscribers and watch time',
    category: 'farming',
    platforms: ['youtube'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'high',
    automationLevel: 60,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'farm-8',
    name: 'Reddit Karma Farming',
    description: 'Farm Reddit karma for account value',
    category: 'farming',
    platforms: ['reddit'],
    expectedRevenue: '$20-60/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'farm-9',
    name: 'Crypto Testnet Farming',
    description: 'Farm crypto testnet tokens',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$30-150/mo',
    riskLevel: 'low',
    automationLevel: 90,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 3,
    timeToProfit: 7
  },
  {
    id: 'farm-10',
    name: 'NFT Whitelist Farming',
    description: 'Farm NFT whitelist spots',
    category: 'farming',
    platforms: ['twitter', 'discord'],
    expectedRevenue: '$100-500/mo',
    riskLevel: 'high',
    automationLevel: 75,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 7,
    timeToProfit: 14
  },
  {
    id: 'farm-11',
    name: 'Play-to-Earn Games',
    description: 'Farm crypto through play-to-earn games',
    category: 'farming',
    platforms: ['telegram', 'discord'],
    expectedRevenue: '$50-300/mo',
    riskLevel: 'medium',
    automationLevel: 80,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 5,
    timeToProfit: 10
  },
  {
    id: 'farm-12',
    name: 'Telegram Channel Growth',
    description: 'Farm Telegram channel subscribers',
    category: 'farming',
    platforms: ['telegram'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 7,
    timeToProfit: 14
  },
  {
    id: 'farm-13',
    name: 'Discord Server Farming',
    description: 'Farm Discord server members',
    category: 'farming',
    platforms: ['discord'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 5,
    timeToProfit: 10
  },
  {
    id: 'farm-14',
    name: 'Twitter Spaces Farming',
    description: 'Farm Twitter Spaces listeners',
    category: 'farming',
    platforms: ['twitter'],
    expectedRevenue: '$30-80/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'farm-15',
    name: 'Instagram Story Views',
    description: 'Farm Instagram story views',
    category: 'farming',
    platforms: ['instagram'],
    expectedRevenue: '$20-60/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 10,
    timeToProfit: 10
  },
  {
    id: 'farm-16',
    name: 'TikTok Live Gifts',
    description: 'Farm TikTok live gifts',
    category: 'farming',
    platforms: ['tiktok'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'medium',
    automationLevel: 60,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 21,
    timeToProfit: 21
  },
  {
    id: 'farm-17',
    name: 'YouTube Live Farming',
    description: 'Farm YouTube live stream viewers',
    category: 'farming',
    platforms: ['youtube'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'farm-18',
    name: 'Facebook Group Farming',
    description: 'Farm Facebook group members',
    category: 'farming',
    platforms: ['facebook'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'medium',
    automationLevel: 65,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'farm-19',
    name: 'DeFi Yield Farming',
    description: 'Farm DeFi yields with multiple wallets',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$100-500/mo',
    riskLevel: 'high',
    automationLevel: 85,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'farm-20',
    name: 'Social Media Points',
    description: 'Farm social media platform points',
    category: 'farming',
    platforms: ['telegram', 'discord', 'twitter'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 90,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'farm-21',
    name: 'Telegram Stars Farming',
    description: 'Farm Telegram Stars through mini apps',
    category: 'farming',
    platforms: ['telegram'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 100,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 3,
    timeToProfit: 5
  },
  {
    id: 'farm-22',
    name: 'Discord Server Boost',
    description: 'Farm Discord server boosts',
    category: 'farming',
    platforms: ['discord'],
    expectedRevenue: '$25-80/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 7,
    timeToProfit: 14
  },
  {
    id: 'farm-23',
    name: 'Twitter NFT Farming',
    description: 'Farm Twitter NFT engagement',
    category: 'farming',
    platforms: ['twitter'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'medium',
    automationLevel: 80,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 7,
    timeToProfit: 14
  },
  {
    id: 'farm-24',
    name: 'Instagram Reel Views',
    description: 'Farm Instagram Reel views',
    category: 'farming',
    platforms: ['instagram'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'medium',
    automationLevel: 75,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'farm-25',
    name: 'TikTok Creator Fund',
    description: 'Farm TikTok Creator Fund earnings',
    category: 'farming',
    platforms: ['tiktok'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'medium',
    automationLevel: 65,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 21,
    timeToProfit: 30
  },
  {
    id: 'farm-26',
    name: 'YouTube Partner Program',
    description: 'Farm YouTube Partner Program eligibility',
    category: 'farming',
    platforms: ['youtube'],
    expectedRevenue: '$100-500/mo',
    riskLevel: 'high',
    automationLevel: 50,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 21,
    timeToProfit: 60
  },
  {
    id: 'farm-27',
    name: 'Facebook Page Farming',
    description: 'Farm Facebook page followers',
    category: 'farming',
    platforms: ['facebook'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'farm-28',
    name: 'Telegram Bot Points',
    description: 'Farm Telegram bot points across multiple bots',
    category: 'farming',
    platforms: ['telegram'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 100,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 3,
    timeToProfit: 5
  },
  {
    id: 'farm-29',
    name: 'Crypto Quest Farming',
    description: 'Farm crypto quest rewards',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'farm-30',
    name: 'Social Quest Platform',
    description: 'Complete social quests on platforms like Galxe',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'low',
    automationLevel: 90,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'farm-31',
    name: 'LayerZero Farming',
    description: 'Farm LayerZero airdrop points',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$100-500/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 14
  },
  {
    id: 'farm-32',
    name: 'ZkSync Farming',
    description: 'Farm ZkSync ecosystem airdrops',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$80-400/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 14
  },
  {
    id: 'farm-33',
    name: 'Starknet Farming',
    description: 'Farm Starknet ecosystem rewards',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$60-300/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 14
  },
  {
    id: 'farm-34',
    name: 'Scroll Farming',
    description: 'Farm Scroll L2 airdrop',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$50-250/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 14
  },
  {
    id: 'farm-35',
    name: 'Linea Farming',
    description: 'Farm Linea ecosystem airdrops',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$40-200/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 14
  },
  {
    id: 'farm-36',
    name: 'Base Farming',
    description: 'Farm Base L2 rewards',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$30-150/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 14
  },
  {
    id: 'farm-37',
    name: 'Mantle Farming',
    description: 'Farm Mantle ecosystem rewards',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$30-150/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 14
  },
  {
    id: 'farm-38',
    name: 'Arbitrum Farming',
    description: 'Farm Arbitrum ecosystem rewards',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 14
  },
  {
    id: 'farm-39',
    name: 'Optimism Farming',
    description: 'Farm Optimism ecosystem rewards',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$40-180/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 14
  },
  {
    id: 'farm-40',
    name: 'Polygon Farming',
    description: 'Farm Polygon ecosystem rewards',
    category: 'farming',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$30-150/mo',
    riskLevel: 'medium',
    automationLevel: 85,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 14
  },

  // ==================== DIRECT SALES (30) ====================
  {
    id: 'sale-1',
    name: 'Sell Warmed Accounts',
    description: 'Sell warmed social media accounts',
    category: 'direct',
    platforms: ['all'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 100,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'sale-2',
    name: 'Sell Telegram Channels',
    description: 'Create and sell Telegram channels',
    category: 'direct',
    platforms: ['telegram'],
    expectedRevenue: '$50-300/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'sale-3',
    name: 'Sell Instagram Accounts',
    description: 'Create and sell Instagram accounts',
    category: 'direct',
    platforms: ['instagram'],
    expectedRevenue: '$50-250/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 21,
    timeToProfit: 28
  },
  {
    id: 'sale-4',
    name: 'Sell TikTok Accounts',
    description: 'Create and sell TikTok accounts',
    category: 'direct',
    platforms: ['tiktok'],
    expectedRevenue: '$40-200/mo',
    riskLevel: 'medium',
    automationLevel: 65,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 21,
    timeToProfit: 28
  },
  {
    id: 'sale-5',
    name: 'Sell Twitter Accounts',
    description: 'Create and sell Twitter accounts',
    category: 'direct',
    platforms: ['twitter'],
    expectedRevenue: '$30-150/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 7,
    timeToProfit: 14
  },
  {
    id: 'sale-6',
    name: 'Sell YouTube Channels',
    description: 'Create and sell YouTube channels',
    category: 'direct',
    platforms: ['youtube'],
    expectedRevenue: '$100-500/mo',
    riskLevel: 'high',
    automationLevel: 50,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 30,
    timeToProfit: 60
  },
  {
    id: 'sale-7',
    name: 'Sell Discord Servers',
    description: 'Create and sell Discord servers',
    category: 'direct',
    platforms: ['discord'],
    expectedRevenue: '$30-150/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 7,
    timeToProfit: 14
  },
  {
    id: 'sale-8',
    name: 'Sell Reddit Accounts',
    description: 'Create and sell Reddit accounts',
    category: 'direct',
    platforms: ['reddit'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'sale-9',
    name: 'Sell Facebook Pages',
    description: 'Create and sell Facebook pages',
    category: 'direct',
    platforms: ['facebook'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'medium',
    automationLevel: 65,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 21,
    timeToProfit: 28
  },
  {
    id: 'sale-10',
    name: 'Sell Aged Accounts',
    description: 'Sell aged social media accounts',
    category: 'direct',
    platforms: ['all'],
    expectedRevenue: '$50-300/mo',
    riskLevel: 'low',
    automationLevel: 90,
    isFree: true,
    minAccounts: 20,
    minWarmingDays: 30,
    timeToProfit: 30
  },
  {
    id: 'sale-11',
    name: 'Sell Premium Usernames',
    description: 'Acquire and sell premium usernames',
    category: 'direct',
    platforms: ['twitter', 'instagram', 'tiktok'],
    expectedRevenue: '$100-1000/mo',
    riskLevel: 'high',
    automationLevel: 40,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 30
  },
  {
    id: 'sale-12',
    name: 'Sell Verified Accounts',
    description: 'Sell verified social media accounts',
    category: 'direct',
    platforms: ['twitter', 'instagram', 'facebook'],
    expectedRevenue: '$200-1000/mo',
    riskLevel: 'high',
    automationLevel: 30,
    isFree: false,
    minAccounts: 3,
    minWarmingDays: 30,
    timeToProfit: 60
  },
  {
    id: 'sale-13',
    name: 'Sell Telegram Numbers',
    description: 'Sell Telegram virtual numbers',
    category: 'direct',
    platforms: ['telegram'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 90,
    isFree: true,
    minAccounts: 20,
    minWarmingDays: 3,
    timeToProfit: 7
  },
  {
    id: 'sale-14',
    name: 'Sell Instagram Themes',
    description: 'Create and sell themed Instagram accounts',
    category: 'direct',
    platforms: ['instagram'],
    expectedRevenue: '$30-150/mo',
    riskLevel: 'medium',
    automationLevel: 60,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 21,
    timeToProfit: 28
  },
  {
    id: 'sale-15',
    name: 'Sell TikTok Themes',
    description: 'Create and sell themed TikTok accounts',
    category: 'direct',
    platforms: ['tiktok'],
    expectedRevenue: '$30-150/mo',
    riskLevel: 'medium',
    automationLevel: 55,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 21,
    timeToProfit: 28
  },
  {
    id: 'sale-16',
    name: 'Sell Niche Accounts',
    description: 'Create and sell niche-specific accounts',
    category: 'direct',
    platforms: ['all'],
    expectedRevenue: '$50-250/mo',
    riskLevel: 'medium',
    automationLevel: 65,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 21,
    timeToProfit: 28
  },
  {
    id: 'sale-17',
    name: 'Sell Crypto Twitter',
    description: 'Sell crypto-focused Twitter accounts',
    category: 'direct',
    platforms: ['twitter'],
    expectedRevenue: '$80-400/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'sale-18',
    name: 'Sell Telegram Crypto Channels',
    description: 'Sell crypto Telegram channels',
    category: 'direct',
    platforms: ['telegram'],
    expectedRevenue: '$100-500/mo',
    riskLevel: 'low',
    automationLevel: 80,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'sale-19',
    name: 'Sell Gaming Discord',
    description: 'Sell gaming-focused Discord servers',
    category: 'direct',
    platforms: ['discord'],
    expectedRevenue: '$50-250/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 10,
    timeToProfit: 14
  },
  {
    id: 'sale-20',
    name: 'Sell Influencer Accounts',
    description: 'Create and sell influencer-ready accounts',
    category: 'direct',
    platforms: ['instagram', 'tiktok', 'youtube'],
    expectedRevenue: '$200-1000/mo',
    riskLevel: 'high',
    automationLevel: 40,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 60,
    timeToProfit: 90
  },
  {
    id: 'sale-21',
    name: 'Sell Business Accounts',
    description: 'Sell business-ready social accounts',
    category: 'direct',
    platforms: ['instagram', 'facebook', 'twitter'],
    expectedRevenue: '$100-500/mo',
    riskLevel: 'medium',
    automationLevel: 60,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 21,
    timeToProfit: 30
  },
  {
    id: 'sale-22',
    name: 'Sell WhatsApp Business',
    description: 'Sell WhatsApp Business accounts',
    category: 'direct',
    platforms: ['whatsapp'],
    expectedRevenue: '$30-120/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'sale-23',
    name: 'Sell Telegram Bot Accounts',
    description: 'Sell Telegram bot-ready accounts',
    category: 'direct',
    platforms: ['telegram'],
    expectedRevenue: '$20-80/mo',
    riskLevel: 'low',
    automationLevel: 90,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 5,
    timeToProfit: 7
  },
  {
    id: 'sale-24',
    name: 'Sell Monetized YouTube',
    description: 'Sell monetized YouTube channels',
    category: 'direct',
    platforms: ['youtube'],
    expectedRevenue: '$300-1500/mo',
    riskLevel: 'high',
    automationLevel: 35,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 60,
    timeToProfit: 90
  },
  {
    id: 'sale-25',
    name: 'Sell TikTok Shop Ready',
    description: 'Sell TikTok Shop ready accounts',
    category: 'direct',
    platforms: ['tiktok'],
    expectedRevenue: '$100-400/mo',
    riskLevel: 'high',
    automationLevel: 45,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 30,
    timeToProfit: 45
  },
  {
    id: 'sale-26',
    name: 'Sell Instagram Shop Ready',
    description: 'Sell Instagram Shop ready accounts',
    category: 'direct',
    platforms: ['instagram'],
    expectedRevenue: '$80-300/mo',
    riskLevel: 'medium',
    automationLevel: 50,
    isFree: true,
    minAccounts: 3,
    minWarmingDays: 30,
    timeToProfit: 45
  },
  {
    id: 'sale-27',
    name: 'Sell Reddit Karma Accounts',
    description: 'Sell high-karma Reddit accounts',
    category: 'direct',
    platforms: ['reddit'],
    expectedRevenue: '$30-150/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 21,
    timeToProfit: 28
  },
  {
    id: 'sale-28',
    name: 'Sell Telegram Premium',
    description: 'Sell Telegram Premium accounts',
    category: 'direct',
    platforms: ['telegram'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 85,
    isFree: false,
    minAccounts: 5,
    minWarmingDays: 7,
    timeToProfit: 14
  },
  {
    id: 'sale-29',
    name: 'Sell Cross-Platform Bundles',
    description: 'Sell account bundles across platforms',
    category: 'direct',
    platforms: ['all'],
    expectedRevenue: '$150-600/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 15,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'sale-30',
    name: 'Sell Location-Specific',
    description: 'Sell accounts with specific locations',
    category: 'direct',
    platforms: ['instagram', 'facebook', 'twitter'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'medium',
    automationLevel: 60,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 21,
    timeToProfit: 28
  },

  // ==================== ARBITRAGE (30) ====================
  {
    id: 'arb-1',
    name: 'Traffic Arbitrage TG→IG',
    description: 'Redirect traffic from Telegram to Instagram',
    category: 'arbitrage',
    platforms: ['telegram', 'instagram'],
    expectedRevenue: '$100-300/mo',
    riskLevel: 'high',
    automationLevel: 70,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'arb-2',
    name: 'Traffic Arbitrage TT→TG',
    description: 'Redirect traffic from TikTok to Telegram',
    category: 'arbitrage',
    platforms: ['tiktok', 'telegram'],
    expectedRevenue: '$150-500/mo',
    riskLevel: 'high',
    automationLevel: 65,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 21,
    timeToProfit: 21
  },
  {
    id: 'arb-3',
    name: 'Traffic Arbitrage IG→TG',
    description: 'Redirect traffic from Instagram to Telegram',
    category: 'arbitrage',
    platforms: ['instagram', 'telegram'],
    expectedRevenue: '$120-400/mo',
    riskLevel: 'high',
    automationLevel: 65,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 21,
    timeToProfit: 21
  },
  {
    id: 'arb-4',
    name: 'Traffic Arbitrage YT→TG',
    description: 'Redirect traffic from YouTube to Telegram',
    category: 'arbitrage',
    platforms: ['youtube', 'telegram'],
    expectedRevenue: '$100-400/mo',
    riskLevel: 'medium',
    automationLevel: 60,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 21,
    timeToProfit: 28
  },
  {
    id: 'arb-5',
    name: 'Traffic Arbitrage TW→TG',
    description: 'Redirect traffic from Twitter to Telegram',
    category: 'arbitrage',
    platforms: ['twitter', 'telegram'],
    expectedRevenue: '$80-300/mo',
    riskLevel: 'medium',
    automationLevel: 75,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'arb-6',
    name: 'Crypto Traffic Arbitrage',
    description: 'Arbitrage crypto traffic across platforms',
    category: 'arbitrage',
    platforms: ['twitter', 'telegram', 'discord'],
    expectedRevenue: '$200-800/mo',
    riskLevel: 'high',
    automationLevel: 80,
    isFree: true,
    minAccounts: 15,
    minWarmingDays: 10,
    timeToProfit: 14
  },
  {
    id: 'arb-7',
    name: 'Gambling Traffic Arbitrage',
    description: 'Arbitrage gambling traffic',
    category: 'arbitrage',
    platforms: ['telegram', 'instagram', 'tiktok'],
    expectedRevenue: '$250-1000/mo',
    riskLevel: 'extreme',
    automationLevel: 75,
    isFree: true,
    minAccounts: 15,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'arb-8',
    name: 'Dating Traffic Arbitrage',
    description: 'Arbitrage dating traffic',
    category: 'arbitrage',
    platforms: ['instagram', 'tiktok', 'facebook'],
    expectedRevenue: '$150-600/mo',
    riskLevel: 'high',
    automationLevel: 70,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 21,
    timeToProfit: 21
  },
  {
    id: 'arb-9',
    name: 'Nutra Traffic Arbitrage',
    description: 'Arbitrage nutra/health traffic',
    category: 'arbitrage',
    platforms: ['instagram', 'tiktok', 'facebook'],
    expectedRevenue: '$100-400/mo',
    riskLevel: 'medium',
    automationLevel: 65,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'arb-10',
    name: 'E-commerce Traffic Arbitrage',
    description: 'Arbitrage e-commerce traffic',
    category: 'arbitrage',
    platforms: ['instagram', 'tiktok', 'youtube'],
    expectedRevenue: '$80-300/mo',
    riskLevel: 'medium',
    automationLevel: 70,
    isFree: true,
    minAccounts: 8,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'arb-11',
    name: 'Adult Traffic Arbitrage',
    description: 'Arbitrage adult traffic',
    category: 'arbitrage',
    platforms: ['twitter', 'telegram', 'reddit'],
    expectedRevenue: '$300-1200/mo',
    riskLevel: 'extreme',
    automationLevel: 80,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'arb-12',
    name: 'Forex Traffic Arbitrage',
    description: 'Arbitrage forex/trading traffic',
    category: 'arbitrage',
    platforms: ['telegram', 'instagram', 'youtube'],
    expectedRevenue: '$200-800/mo',
    riskLevel: 'high',
    automationLevel: 70,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 14,
    timeToProfit: 14
  },
  {
    id: 'arb-13',
    name: 'NFT Traffic Arbitrage',
    description: 'Arbitrage NFT traffic',
    category: 'arbitrage',
    platforms: ['twitter', 'discord', 'telegram'],
    expectedRevenue: '$150-600/mo',
    riskLevel: 'high',
    automationLevel: 80,
    isFree: true,
    minAccounts: 15,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'arb-14',
    name: 'Software Traffic Arbitrage',
    description: 'Arbitrage software/SaaS traffic',
    category: 'arbitrage',
    platforms: ['youtube', 'twitter', 'telegram'],
    expectedRevenue: '$60-250/mo',
    riskLevel: 'medium',
    automationLevel: 75,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'arb-15',
    name: 'Education Traffic Arbitrage',
    description: 'Arbitrage education/course traffic',
    category: 'arbitrage',
    platforms: ['instagram', 'youtube', 'telegram'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 10,
    timeToProfit: 14
  },
  {
    id: 'arb-16',
    name: 'Gaming Traffic Arbitrage',
    description: 'Arbitrage gaming traffic',
    category: 'arbitrage',
    platforms: ['discord', 'youtube', 'tiktok'],
    expectedRevenue: '$80-300/mo',
    riskLevel: 'medium',
    automationLevel: 75,
    isFree: true,
    minAccounts: 8,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'arb-17',
    name: 'Finance Traffic Arbitrage',
    description: 'Arbitrage finance/investment traffic',
    category: 'arbitrage',
    platforms: ['twitter', 'youtube', 'telegram'],
    expectedRevenue: '$150-500/mo',
    riskLevel: 'high',
    automationLevel: 70,
    isFree: true,
    minAccounts: 8,
    minWarmingDays: 10,
    timeToProfit: 14
  },
  {
    id: 'arb-18',
    name: 'Betting Traffic Arbitrage',
    description: 'Arbitrage sports betting traffic',
    category: 'arbitrage',
    platforms: ['telegram', 'twitter', 'instagram'],
    expectedRevenue: '$200-700/mo',
    riskLevel: 'high',
    automationLevel: 75,
    isFree: true,
    minAccounts: 10,
    minWarmingDays: 10,
    timeToProfit: 14
  },
  {
    id: 'arb-19',
    name: 'Fashion Traffic Arbitrage',
    description: 'Arbitrage fashion/retail traffic',
    category: 'arbitrage',
    platforms: ['instagram', 'tiktok', 'youtube'],
    expectedRevenue: '$60-200/mo',
    riskLevel: 'low',
    automationLevel: 65,
    isFree: true,
    minAccounts: 8,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'arb-20',
    name: 'Fitness Traffic Arbitrage',
    description: 'Arbitrage fitness/health traffic',
    category: 'arbitrage',
    platforms: ['instagram', 'tiktok', 'youtube'],
    expectedRevenue: '$50-180/mo',
    riskLevel: 'low',
    automationLevel: 65,
    isFree: true,
    minAccounts: 8,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'arb-21',
    name: 'Tech Traffic Arbitrage',
    description: 'Arbitrage tech/gadget traffic',
    category: 'arbitrage',
    platforms: ['youtube', 'twitter', 'telegram'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 75,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 7,
    timeToProfit: 10
  },
  {
    id: 'arb-22',
    name: 'Travel Traffic Arbitrage',
    description: 'Arbitrage travel/tourism traffic',
    category: 'arbitrage',
    platforms: ['instagram', 'youtube', 'tiktok'],
    expectedRevenue: '$50-200/mo',
    riskLevel: 'low',
    automationLevel: 60,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'arb-23',
    name: 'Food Traffic Arbitrage',
    description: 'Arbitrage food/restaurant traffic',
    category: 'arbitrage',
    platforms: ['instagram', 'tiktok', 'youtube'],
    expectedRevenue: '$30-120/mo',
    riskLevel: 'low',
    automationLevel: 60,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'arb-24',
    name: 'Pet Traffic Arbitrage',
    description: 'Arbitrage pet-related traffic',
    category: 'arbitrage',
    platforms: ['instagram', 'tiktok', 'youtube'],
    expectedRevenue: '$30-100/mo',
    riskLevel: 'low',
    automationLevel: 65,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 10,
    timeToProfit: 14
  },
  {
    id: 'arb-25',
    name: 'Music Traffic Arbitrage',
    description: 'Arbitrage music/artist traffic',
    category: 'arbitrage',
    platforms: ['youtube', 'tiktok', 'instagram'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 70,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 10,
    timeToProfit: 14
  },
  {
    id: 'arb-26',
    name: 'Real Estate Traffic Arbitrage',
    description: 'Arbitrage real estate traffic',
    category: 'arbitrage',
    platforms: ['instagram', 'facebook', 'youtube'],
    expectedRevenue: '$100-400/mo',
    riskLevel: 'medium',
    automationLevel: 55,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'arb-27',
    name: 'Auto Traffic Arbitrage',
    description: 'Arbitrage automotive traffic',
    category: 'arbitrage',
    platforms: ['youtube', 'instagram', 'facebook'],
    expectedRevenue: '$60-200/mo',
    riskLevel: 'medium',
    automationLevel: 60,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'arb-28',
    name: 'Home Decor Traffic Arbitrage',
    description: 'Arbitrage home/decor traffic',
    category: 'arbitrage',
    platforms: ['instagram', 'pinterest', 'youtube'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 60,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'arb-29',
    name: 'Baby Products Traffic Arbitrage',
    description: 'Arbitrage baby/parenting traffic',
    category: 'arbitrage',
    platforms: ['instagram', 'facebook', 'youtube'],
    expectedRevenue: '$40-150/mo',
    riskLevel: 'low',
    automationLevel: 60,
    isFree: true,
    minAccounts: 5,
    minWarmingDays: 14,
    timeToProfit: 21
  },
  {
    id: 'arb-30',
    name: 'Multi-Niche Traffic Arbitrage',
    description: 'Arbitrage traffic across multiple niches',
    category: 'arbitrage',
    platforms: ['all'],
    expectedRevenue: '$300-1200/mo',
    riskLevel: 'high',
    automationLevel: 70,
    isFree: true,
    minAccounts: 20,
    minWarmingDays: 14,
    timeToProfit: 21
  }
];

// Helper function to get schemes by category
export function getSchemesByCategory(category: SchemeCategory): MonetizationSchemeDefinition[] {
  return MONETIZATION_SCHEMES.filter(s => s.category === category);
}

// Helper function to get schemes by platform
export function getSchemesByPlatform(platform: Platform): MonetizationSchemeDefinition[] {
  return MONETIZATION_SCHEMES.filter(s => 
    s.platforms.includes(platform) || s.platforms.includes('all')
  );
}

// Helper function to get schemes by risk level
export function getSchemesByRiskLevel(riskLevel: RiskLevel): MonetizationSchemeDefinition[] {
  return MONETIZATION_SCHEMES.filter(s => s.riskLevel === riskLevel);
}

// Get all unique platforms from schemes
export function getAllPlatforms(): Platform[] {
  const platforms = new Set<Platform>();
  MONETIZATION_SCHEMES.forEach(s => {
    s.platforms.forEach(p => platforms.add(p));
  });
  return Array.from(platforms);
}

// Get scheme statistics
export function getSchemeStats() {
  return {
    total: MONETIZATION_SCHEMES.length,
    byCategory: {
      cpa: getSchemesByCategory('cpa').length,
      affiliate: getSchemesByCategory('affiliate').length,
      farming: getSchemesByCategory('farming').length,
      direct: getSchemesByCategory('direct').length,
      arbitrage: getSchemesByCategory('arbitrage').length
    },
    byRiskLevel: {
      low: getSchemesByRiskLevel('low').length,
      medium: getSchemesByRiskLevel('medium').length,
      high: getSchemesByRiskLevel('high').length,
      extreme: getSchemesByRiskLevel('extreme').length
    },
    freeSchemes: MONETIZATION_SCHEMES.filter(s => s.isFree).length,
    avgAutomationLevel: Math.round(
      MONETIZATION_SCHEMES.reduce((acc, s) => acc + s.automationLevel, 0) / MONETIZATION_SCHEMES.length
    )
  };
}

export default MONETIZATION_SCHEMES;
