// API: Генерация легенд аккаунтов (УРОВЕНЬ 4, функция 17)
import { NextRequest, NextResponse } from 'next/server';
import { generateAccountLegend } from '@/lib/advanced-ai-engine';
import { db } from '@/lib/db';
import { nanoid } from 'nanoid';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { channelTheme, influencerData, userId, saveToDb } = body;
    
    if (!channelTheme) {
      return NextResponse.json(
        { error: 'Missing required field: channelTheme' },
        { status: 400 }
      );
    }
    
    const legend = await generateAccountLegend(channelTheme, influencerData, userId);
    
    // Сохраняем в базу если нужно
    let savedLegend: Awaited<ReturnType<typeof db.accountLegend.create>> | null = null;
    if (saveToDb && userId) {
      savedLegend = await db.accountLegend.create({
        data: {
          id: nanoid(),
          age: legend.age,
          city: legend.city,
          occupation: legend.occupation,
          hobbies: JSON.stringify(legend.hobbies),
          bio: legend.bio,
          channelTheme,
          autoGenerated: true,
          updatedAt: new Date(),
        },
      });
    }
    
    return NextResponse.json({
      success: true,
      legend,
      savedLegend,
    });
  } catch (error) {
    console.error('[LegendGenerate API] Error:', error);
    return NextResponse.json(
      { error: 'Failed to generate legend', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}
