import { NextResponse } from 'next/server';

// Получение всех методов монетизации
export async function GET() {
  const methods = [
    {
      id: 'p2p_rent',
      name: 'P2P Аренда аккаунтов',
      description: 'Сдавайте аккаунты в аренду другим арбитражникам. Пассивный доход без риска бана.',
      color: '#00D26A',
      minAccounts: 1,
      minQuality: 30,
      estimatedROI: '$5-12/день за аккаунт',
      riskLevel: 'low',
      setupTime: '5 минут',
      features: [
        'Пассивный доход',
        'Минимальный риск бана',
        'Гибкий график',
        'Страховка от блоков',
      ],
      warnings: [],
      requirements: [
        'Аккаунт старше 7 дней',
        'Наличие аватара',
      ],
      recommended: true,
      popular: true,
    },
    {
      id: 'ofm_chatter',
      name: 'OFM Чаттер (OnlyFans)',
      description: 'Переписка с фанатами моделей OnlyFans. Высокий доход с PPV контента.',
      color: '#FF6B9D',
      minAccounts: 1,
      minQuality: 50,
      estimatedROI: '$500-2000/мес',
      riskLevel: 'low',
      setupTime: '30 минут',
      features: [
        'Высокая оплата за PPV',
        'Бонусы от моделей',
        'Гибкий график',
        'Обучение предоставляется',
      ],
      warnings: [
        'Требует навыков общения',
        'Нужен разговорный английский',
      ],
      requirements: [
        'Аккаунт старше 14 дней',
        'Качество 50+',
      ],
      popular: true,
    },
    {
      id: 'gambling',
      name: 'Gambling (Казино/Ставки)',
      description: 'Привлечение игроков в казино и букмекеры. CPA и RevShare модели.',
      color: '#FFB800',
      minAccounts: 3,
      minQuality: 60,
      estimatedROI: '$50-500/день',
      riskLevel: 'high',
      setupTime: '1-2 часа',
      features: [
        'Высокий CPA ($50-200)',
        'RevShare до 50%',
        'Много офферов',
        'AI-креативы',
      ],
      warnings: [
        'Высокий риск бана',
        'Требует прогрева',
        'Необходимы прокси',
      ],
      requirements: [
        'Минимум 3 аккаунта',
        'Качество 60+',
        'Индивидуальные прокси',
      ],
    },
    {
      id: 'dating',
      name: 'Dating (Дейтинг)',
      description: 'Привлечение пользователей на дейтинг-платформы. Стабильный доход.',
      color: '#FF4D4D',
      minAccounts: 2,
      minQuality: 45,
      estimatedROI: '$30-200/день',
      riskLevel: 'medium',
      setupTime: '1 час',
      features: [
        'Стабильный спрос',
        'SOI/DOI офферы',
        'Высокая конверсия',
        'Много гео',
      ],
      warnings: [
        'Средний риск бана',
        'Требует качественных креативов',
      ],
      requirements: [
        'Минимум 2 аккаунта',
        'Качество 45+',
      ],
      popular: true,
    },
    {
      id: 'crypto',
      name: 'Crypto (Криптовалюты)',
      description: 'Привлечение рефералов на криптобиржи и проекты. Высокий CPA.',
      color: '#6C63FF',
      minAccounts: 2,
      minQuality: 55,
      estimatedROI: '$100-1000/день',
      riskLevel: 'medium',
      setupTime: '2 часа',
      features: [
        'CPA до $500',
        'RevShare до 50%',
        'Быстрые выплаты',
        'Глобальный рынок',
      ],
      warnings: [
        'Требует знаний крипты',
        'Средний риск бана',
      ],
      requirements: [
        'Минимум 2 аккаунта',
        'Качество 55+',
        'Прокси для каждого аккаунта',
      ],
    },
    {
      id: 'ecommerce',
      name: 'E-commerce (Товарка)',
      description: 'Продвижение товаров через Telegram. Дропшиппинг и CPA.',
      color: '#00B8D4',
      minAccounts: 1,
      minQuality: 40,
      estimatedROI: '$20-150/день',
      riskLevel: 'low',
      setupTime: '1 час',
      features: [
        'Низкий риск бана',
        'Много товарок',
        'Белый метод',
        'Стабильный доход',
      ],
      warnings: [
        'Требует качественных фото',
        'Конкуренция',
      ],
      requirements: [
        'Качество 40+',
        'Прокси рекомендуются',
      ],
    },
    {
      id: 'influencer',
      name: 'Influencer (Блогеры)',
      description: 'Управление аккаунтами блогеров. Комментинг и комьюнити.',
      color: '#FF9500',
      minAccounts: 1,
      minQuality: 70,
      estimatedROI: '$200-1000/мес',
      riskLevel: 'low',
      setupTime: '30 минут',
      features: [
        'Минимальный риск',
        'Долгосрочное сотрудничество',
        'Бонусы за активность',
        'Рост аккаунтов',
      ],
      warnings: [
        'Требует качественных аккаунтов',
        'Необходимы навыки общения',
      ],
      requirements: [
        'Качество 70+',
        'Аккаунт старше 30 дней',
      ],
    },
    {
      id: 'nutra',
      name: 'Nutra (Нутра)',
      description: 'Продвижение БАДов, косметики. Высокий ROI на сложных гео.',
      color: '#4CAF50',
      minAccounts: 2,
      minQuality: 50,
      estimatedROI: '$50-300/день',
      riskLevel: 'medium',
      setupTime: '1.5 часа',
      features: [
        'Высокий ROI',
        'Много офферов',
        'Трай-апс',
        'Глобальные гео',
      ],
      warnings: [
        'Требует креативов',
        'Средний риск бана',
      ],
      requirements: [
        'Минимум 2 аккаунта',
        'Качество 50+',
      ],
    },
    {
      id: 'crypto_p2p',
      name: 'Crypto P2P Арбитраж',
      description: 'P2P торговля криптовалютой через Telegram. Спреды 2-5%.',
      color: '#9C27B0',
      minAccounts: 3,
      minQuality: 65,
      estimatedROI: '$100-500/день',
      riskLevel: 'medium',
      setupTime: '3 часа',
      features: [
        'Без офферов',
        'Спреды 2-5%',
        'Быстрые сделки',
        'Минимальные риски бана',
      ],
      warnings: [
        'Требует оборотный капитал',
        'Нужны верифицированные карты',
      ],
      requirements: [
        'Минимум 3 аккаунта',
        'Качество 65+',
        'Капитал от $500',
      ],
    },
    {
      id: 'affiliate_channel',
      name: 'Арбитраж каналов',
      description: 'Создание и рост Telegram каналов с последующей монетизацией.',
      color: '#E91E63',
      minAccounts: 1,
      minQuality: 35,
      estimatedROI: '$100-2000/мес',
      riskLevel: 'low',
      setupTime: '2 часа',
      features: [
        'Долгосрочный актив',
        'Продажа рекламы',
        'Пассивный доход',
        'Рост капитализации',
      ],
      warnings: [
        'Требует времени на рост',
        'Нужен контент',
      ],
      requirements: [
        'Качество 35+',
        'Постоянный доступ',
      ],
      recommended: true,
    },
    {
      id: 'referal_network',
      name: 'Реферальная сеть',
      description: 'Построение реферальной сети в различных проектах.',
      color: '#607D8B',
      minAccounts: 1,
      minQuality: 40,
      estimatedROI: '$50-500/мес',
      riskLevel: 'low',
      setupTime: '1 час',
      features: [
        'Пассивный доход',
        'Масштабирование',
        'Минимальные риски',
        'Много проектов',
      ],
      warnings: [
        'Требует времени на построение',
      ],
      requirements: [
        'Качество 40+',
      ],
    },
    {
      id: 'commenting',
      name: 'Комментинг сервис',
      description: 'Комментирование постов в каналах для продвижения.',
      color: '#795548',
      minAccounts: 5,
      minQuality: 30,
      estimatedROI: '$30-100/день',
      riskLevel: 'medium',
      setupTime: '30 минут',
      features: [
        'Быстрый старт',
        'Много заказов',
        'Гибкий график',
      ],
      warnings: [
        'Риск бана при спаме',
        'Требует много аккаунтов',
      ],
      requirements: [
        'Минимум 5 аккаунтов',
        'Прокси для каждого',
      ],
    },
  ];

  return NextResponse.json({
    success: true,
    methods,
    total: methods.length,
  });
}
