import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { nanoid } from 'nanoid';

// Default settings structure
const defaultSettings = {
  // Appearance
  theme: 'dark',
  language: 'ru',
  
  // Notifications
  notifications: {
    enabled: true,
    sound: true,
    desktop: false,
    email: false,
  },
  
  // Risk Assistant
  riskAssistant: {
    enabled: true,
    threshold: 'medium' as const,
    autoGenerateDisclaimers: true,
  },
  
  // Automation
  automation: {
    autoPauseOnCpa: false,
    telegramNotifications: false,
    telegramChatId: '',
  },
  
  // Voice
  voice: {
    enabled: false,
    provider: 'browser' as const,
    voiceId: '',
  },
  
  // API Settings (existing)
  deepseekApiKey: '',
  telegramApiId: '',
  telegramApiHash: '',
  proxyServiceUrl: '',
  maxCommentsPerAccount: 50,
  delayMin: 30,
  delayMax: 120,
  delayRandom: true,
};

// GET /api/settings - Get app settings
export async function GET() {
  try {
    // Get or create settings (assuming single user for now)
    let settings = await db.globalAppSettings.findFirst();

    if (!settings) {
      // Create default settings
      settings = await db.globalAppSettings.create({
        data: {
          id: nanoid(),
          deepseekApiKey: '',
          telegramApiId: '',
          telegramApiHash: '',
          proxyServiceUrl: '',
          maxCommentsPerAccount: 50,
          delayMin: 30,
          delayMax: 120,
          delayRandom: true,
          autoPauseOnCpa: false,
          telegramChatId: '',
          riskAssistantEnabled: true,
          riskThreshold: 'medium',
          autoGenerateDisclaimers: true,
          logWarnings: true,
          userId: 'default',
          updatedAt: new Date(),
        }
      });
    }

    // Map database settings to response format
    const response = {
      // Appearance (from database or defaults)
      theme: (settings as any).theme || defaultSettings.theme,
      language: (settings as any).language || defaultSettings.language,
      
      // Notifications
      notifications: {
        enabled: (settings as any).notificationsEnabled ?? defaultSettings.notifications.enabled,
        sound: (settings as any).notificationsSound ?? defaultSettings.notifications.sound,
        desktop: (settings as any).notificationsDesktop ?? defaultSettings.notifications.desktop,
        email: (settings as any).notificationsEmail ?? defaultSettings.notifications.email,
      },
      
      // Risk Assistant
      riskAssistant: {
        enabled: settings.riskAssistantEnabled ?? defaultSettings.riskAssistant.enabled,
        threshold: settings.riskThreshold || defaultSettings.riskAssistant.threshold,
        autoGenerateDisclaimers: settings.autoGenerateDisclaimers ?? defaultSettings.riskAssistant.autoGenerateDisclaimers,
      },
      
      // Automation
      automation: {
        autoPauseOnCpa: settings.autoPauseOnCpa ?? defaultSettings.automation.autoPauseOnCpa,
        telegramNotifications: (settings as any).telegramNotifications ?? defaultSettings.automation.telegramNotifications,
        telegramChatId: settings.telegramChatId || defaultSettings.automation.telegramChatId,
      },
      
      // Voice
      voice: {
        enabled: (settings as any).voiceEnabled ?? defaultSettings.voice.enabled,
        provider: (settings as any).voiceProvider || defaultSettings.voice.provider,
        voiceId: (settings as any).voiceId || defaultSettings.voice.voiceId,
      },
      
      // API Settings
      deepseekApiKey: settings.deepseekApiKey || '',
      telegramApiId: settings.telegramApiId || '',
      telegramApiHash: settings.telegramApiHash || '',
      proxyServiceUrl: settings.proxyServiceUrl || '',
      maxCommentsPerAccount: settings.maxCommentsPerAccount,
      delayMin: settings.delayMin,
      delayMax: settings.delayMax,
      delayRandom: settings.delayRandom,
    };

    return NextResponse.json(response);
  } catch (error) {
    console.error('Error fetching settings:', error);
    return NextResponse.json(
      { error: 'Failed to fetch settings' },
      { status: 500 }
    );
  }
}

// POST /api/settings - Update app settings (supports partial updates)
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    
    // Get existing settings
    let settings = await db.globalAppSettings.findFirst();

    // Prepare update data
    const updateData: Record<string, any> = {};
    
    // Flatten nested objects for database
    if (body.theme) updateData.theme = body.theme;
    if (body.language) updateData.language = body.language;
    
    if (body.notifications) {
      if (body.notifications.enabled !== undefined) updateData.notificationsEnabled = body.notifications.enabled;
      if (body.notifications.sound !== undefined) updateData.notificationsSound = body.notifications.sound;
      if (body.notifications.desktop !== undefined) updateData.notificationsDesktop = body.notifications.desktop;
      if (body.notifications.email !== undefined) updateData.notificationsEmail = body.notifications.email;
    }
    
    if (body.riskAssistant) {
      if (body.riskAssistant.enabled !== undefined) updateData.riskAssistantEnabled = body.riskAssistant.enabled;
      if (body.riskAssistant.threshold) updateData.riskThreshold = body.riskAssistant.threshold;
      if (body.riskAssistant.autoGenerateDisclaimers !== undefined) updateData.autoGenerateDisclaimers = body.riskAssistant.autoGenerateDisclaimers;
    }
    
    if (body.automation) {
      if (body.automation.autoPauseOnCpa !== undefined) updateData.autoPauseOnCpa = body.automation.autoPauseOnCpa;
      if (body.automation.telegramNotifications !== undefined) updateData.telegramNotifications = body.automation.telegramNotifications;
      if (body.automation.telegramChatId !== undefined) updateData.telegramChatId = body.automation.telegramChatId;
    }
    
    if (body.voice) {
      if (body.voice.enabled !== undefined) updateData.voiceEnabled = body.voice.enabled;
      if (body.voice.provider) updateData.voiceProvider = body.voice.provider;
      if (body.voice.voiceId !== undefined) updateData.voiceId = body.voice.voiceId;
    }
    
    // Direct fields
    if (body.deepseekApiKey !== undefined) updateData.deepseekApiKey = body.deepseekApiKey;
    if (body.telegramApiId !== undefined) updateData.telegramApiId = body.telegramApiId;
    if (body.telegramApiHash !== undefined) updateData.telegramApiHash = body.telegramApiHash;
    if (body.proxyServiceUrl !== undefined) updateData.proxyServiceUrl = body.proxyServiceUrl;
    if (body.maxCommentsPerAccount !== undefined) updateData.maxCommentsPerAccount = body.maxCommentsPerAccount;
    if (body.delayMin !== undefined) updateData.delayMin = body.delayMin;
    if (body.delayMax !== undefined) updateData.delayMax = body.delayMax;
    if (body.delayRandom !== undefined) updateData.delayRandom = body.delayRandom;

    if (!settings) {
      // Create new settings
      settings = await db.globalAppSettings.create({
        data: {
          id: nanoid(),
          ...updateData,
          userId: 'default',
          updatedAt: new Date(),
        }
      });
    } else {
      // Update existing settings
      settings = await db.globalAppSettings.update({
        where: { id: settings.id },
        data: updateData
      });
    }

    return NextResponse.json({
      success: true,
      message: 'Settings saved successfully'
    });
  } catch (error) {
    console.error('Error updating settings:', error);
    return NextResponse.json(
      { error: 'Failed to update settings' },
      { status: 500 }
    );
  }
}

// PUT /api/settings - Full update (backward compatibility)
export async function PUT(request: NextRequest) {
  return POST(request);
}
