import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

// GET /api/settings - Get app settings
export async function GET() {
  try {
    // Get or create settings (assuming single user for now)
    let settings = await db.globalAppSettings.findFirst();

    if (!settings) {
      // Create default settings
      settings = await db.globalAppSettings.create({
        data: {
          deepseekApiKey: '',
          telegramApiId: '',
          telegramApiHash: '',
          proxyServiceUrl: '',
          maxCommentsPerAccount: 50,
          delayMin: 30,
          delayMax: 120,
          delayRandom: true,
          autoPauseOnCpa: false,
          telegramChatId: '',
          riskAssistantEnabled: true,
          riskThreshold: 'medium',
          autoGenerateDisclaimers: true,
          logWarnings: true,
          userId: 'default'
        }
      });
    }

    return NextResponse.json({
      settings: {
        deepseekApiKey: settings.deepseekApiKey || '',
        telegramApiId: settings.telegramApiId || '',
        telegramApiHash: settings.telegramApiHash || '',
        proxyServiceUrl: settings.proxyServiceUrl || '',
        maxCommentsPerAccount: settings.maxCommentsPerAccount,
        delayMin: settings.delayMin,
        delayMax: settings.delayMax,
        delayRandom: settings.delayRandom,
        autoPauseOnCpa: settings.autoPauseOnCpa,
        telegramChatId: settings.telegramChatId || '',
        riskAssistantEnabled: settings.riskAssistantEnabled,
        riskThreshold: settings.riskThreshold,
        autoGenerateDisclaimers: settings.autoGenerateDisclaimers,
        logWarnings: settings.logWarnings
      }
    });
  } catch (error) {
    console.error('Error fetching settings:', error);
    return NextResponse.json(
      { error: 'Failed to fetch settings' },
      { status: 500 }
    );
  }
}

// PUT /api/settings - Update app settings
export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    
    // Get existing settings
    let settings = await db.globalAppSettings.findFirst();

    if (!settings) {
      // Create new settings
      settings = await db.globalAppSettings.create({
        data: {
          ...body,
          userId: 'default'
        }
      });
    } else {
      // Update existing settings
      settings = await db.globalAppSettings.update({
        where: { id: settings.id },
        data: body
      });
    }

    return NextResponse.json({
      success: true,
      settings: {
        deepseekApiKey: settings.deepseekApiKey || '',
        telegramApiId: settings.telegramApiId || '',
        telegramApiHash: settings.telegramApiHash || '',
        proxyServiceUrl: settings.proxyServiceUrl || '',
        maxCommentsPerAccount: settings.maxCommentsPerAccount,
        delayMin: settings.delayMin,
        delayMax: settings.delayMax,
        delayRandom: settings.delayRandom,
        autoPauseOnCpa: settings.autoPauseOnCpa,
        telegramChatId: settings.telegramChatId || '',
        riskAssistantEnabled: settings.riskAssistantEnabled,
        riskThreshold: settings.riskThreshold,
        autoGenerateDisclaimers: settings.autoGenerateDisclaimers,
        logWarnings: settings.logWarnings
      }
    });
  } catch (error) {
    console.error('Error updating settings:', error);
    return NextResponse.json(
      { error: 'Failed to update settings' },
      { status: 500 }
    );
  }
}
